
#
# $Id$
#
#

PACKAGE := smppdmplx.core_ax.network

CXXFLAGS:=-I. -I$(SMSC_SRCDIR)/smppdmplx  $(CXXFLAGS)

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules
