
#
# $Id$
#
#

PACKAGE := smppdmplx

CXXFLAGS := -Ismppdmplx/ -I. $(CXXFLAGS)
#__LIBRARIES :=-L$(SMSC_BUILDDIR)/bin -lsocket -lnsl -lutil-config -lutil-xml -llogger -lxerces-c

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules
