// NOTE: Do NOT edit this file (it is auto-generated).
// Instead, edit message-cpp.tmpl and regenerate.

#ifndef __SCAG_PVSS_PVAP_BC_INC_HPP__
#define __SCAG_PVSS_PVAP_BC_INC_HPP__

#include "util/int.h"
#include <string>
#include "scag/pvss/pvap/Exceptions.h"

// #include "scag/pvss/pvap/TimePolicy.h"
#include "scag/pvss/pvap/TimePolicyFiller.h"

#include "scag/pvss/packets/IncCommand.h"





namespace scag2{
namespace pvss{
namespace pvap{

class PVAPBC;

class BC_INC
{
protected:
    static const int varNameTag = 20;
    static const int timePolicyTag = 21;
    static const int intValueTag = 25;

public:
    BC_INC( int seqNum ) :
    owned_(true),
    data_(new IncCommand(seqNum))
    {
    }

    BC_INC( IncCommand* other ) :
    owned_(false),
    data_(other)
    {
    }

    ~BC_INC() {
        if ( data_ && owned_ ) delete data_;
    }

    void clear()
    {
        if ( ! data_ ) return;
        data_->clear();
    }

    IncCommand* pop() {
        IncCommand* rv = data_;
        data_ = 0;
        return rv;
    }

    std::string toString() const
    {
        return data_ ? data_->toString() : "";
    }

    template < class DataStream >
        void serialize( const PVAPBC& proto, DataStream& writer ) const throw (PvapException)
    {
        if ( ! data_ ) return;
        checkFields();
        // mandatory fields
        try {
            // printf( "write pos=%d field=%d\n", ds.getPos(), varNameTag );
            writer.writeTag(varNameTag);
            writer.writeAsciiLV(data_->getVarName());
        } catch ( IOException e ) {
            throw PvapSerializationException( data_->isRequest(),
                                              data_->getSeqNum(),
                                              "writing field varName in BC_INC: %s",
                                              e.what() );
        }
        try {
            // printf( "write pos=%d field=%d\n", ds.getPos(), timePolicyTag );
            writer.writeTag(timePolicyTag);
            {
                TimePolicyFiller helper( data_ );
                helper.serialize( proto, writer );
 
            }
        } catch ( IOException e ) {
            throw PvapSerializationException( data_->isRequest(),
                                              data_->getSeqNum(),
                                              "writing field timePolicy in BC_INC: %s",
                                              e.what() );
        }
        try {
            // printf( "write pos=%d field=%d\n", ds.getPos(), intValueTag );
            writer.writeTag(intValueTag);
            writer.writeIntLV(data_->getIntValue());
        } catch ( IOException e ) {
            throw PvapSerializationException( data_->isRequest(),
                                              data_->getSeqNum(),
                                              "writing field intValue in BC_INC: %s",
                                              e.what() );
        }
        // optional fields
    }

    template <class DataStream> void deserialize( PVAPBC& proto, DataStream& reader )
        throw (PvapException)
    {
        if ( ! data_ ) return;
        clear();
        int tag = -1;
        try {
            do {
                // int pos = int(reader.getPos());
                tag = reader.readTag();
                // printf( "read pos=%d field=%d\n", pos, tag );
                if ( tag == -1 ) break;
                switch(tag) {
                case varNameTag: {
                    data_->setVarName(reader.readAsciiLV());
                    break;
                }
                case timePolicyTag: {
                    TimePolicyFiller helper(data_);
                    helper.deserialize(proto,reader);
                    break;
                }
                case intValueTag: {
                    data_->setIntValue(reader.readIntLV());
                    break;
                }
                default:
                    throw InvalidFieldTypeException(data_->isRequest(),"invalid field in BC_INC", data_->getSeqNum(),tag);
                }
            } while ( true );
        } catch ( IOException e ) {
            throw PvapSerializationException( data_->isRequest(),
                                              data_->getSeqNum(),
                                              "reading field tag=%d of BC_INC: %s",
                                              tag, e.what() );
        }
        checkFields();
    }

    uint32_t getSeqNum() const {
        return data_ ? data_->getSeqNum() : uint32_t(-1);
    }

protected:
    void checkFields() const throw (PvapException)
    {
        // using parent check
        if ( !data_->isValid() ) {
            throw MessageIsBrokenException(data_->isRequest(), "message BC_INC is broken: " + toString(), data_->getSeqNum() );
        }
    }

private:
    BC_INC( const BC_INC& );
    BC_INC& operator = ( const BC_INC& );

protected:
    //static const uint8_t versionMajor=2;
    //static const uint8_t versionMinor=0;

    bool                owned_;
    IncCommand* data_;

};

} // namespace scag2
} // namespace pvss
} // namespace pvap
#endif
