#!/bin/bash

./mv_logs.sh

PARAM="-Ddcpgw -Xmx256m -jar /home/artem/SERVICES/Informer/informer/services/dcpgw/lib/dcpgw.jar "
nohup $JAVA_HOME/bin/java $PARAM 1>logs/out 2>logs/err &
PID=$!
export PID
trap "kill -s SIGTERM $PID;wait $PID; exit" SIGTERM
wait $PID

