#!/bin/bash

./mv_logs.sh
. ./setenv.sh

PARAM="-Ddcpgw -Xmx256m -cp "$CLASSPATH" mobi.eyeline.dcpgw.Gateway"
nohup $JAVA_HOME/bin/java $PARAM 1>logs/out 2>logs/err &
PID=$!
export PID
trap "kill -s SIGTERM $PID;wait $PID; exit" SIGTERM
wait $PID

