#!/bin/bash
if [ -f logs/mtpers.err ]; then
  mv logs/mtpers.err logs/mtpers.err.old
fi
while true;
do
bin/mtpers 1>/dev/null 2>>logs/mtpers.err&
PID=$!
export PID
trap "kill -s SIGTERM $PID;wait $PID; exit" SIGTERM
wait $PID
if [ -f core ]; then
  DATE=`perl -e '($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst)=localtime(time);printf("%04d%02d%02d%02d%02d%02d",$year+1900,$mon+1,$mday,$hour,$min,$sec)'`

  mkdir "$DATE"
  mv core "$DATE"
  mv logs/mtpers.err "$DATE"
  if [ -f logs/mtpers.err.old ]; then
    mv logs/mtpers.err.old "$DATE"
  fi
  mv logs/mtpers.log* "$DATE"
  cp -p bin/mtpers "$DATE"
fi
done
