#!/bin/bash
if [ -f logs/scag.err ]; then
  mv logs/scag.err logs/scag.err.old
fi
while true;
do
bin/scag 1>/dev/null 2>>logs/scag.err&
PID=$!
export PID
trap "kill -s SIGTERM $PID;wait $PID; exit" SIGTERM
wait $PID
if [ -f core ]; then
  DATE=`perl -e '($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst)=localtime(time);printf("%04d%02d%02d%02d%02d%02d",$year+1900,$mon+1,$mday,$hour,$min,$sec)'`

  mkdir "$DATE"
  mv core "$DATE"
  mv logs/scag.err "$DATE"
  if [ -f logs/scag.err.old ]; then
    mv logs/scag.err.old "$DATE"
  fi
  mv logs/scag.log* "$DATE"
  cp -p bin/scag "$DATE"
fi
done
