#
# $Id$
#

CFLAGS := -I. -DASN1_XER_NOT_USED  $(CFLAGS)
CXXFLAGS := -I. -DASN1_XER_NOT_USED $(CXXFLAGS) 
PACKAGE := inman.asn1rt

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules
