# $Id$
CXXFLAGS := $(CXXFLAGS) -I../processor/ros -I../processor/tcap -I../processor/codec -I../processor/asn1rt -I../processor -I../processor/ulcodec
PACKAGE := mtsmsme.comp

LDFLAGS := $(LDFLAGS) -z verbose

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules


	

