// NOTE: Do NOT edit this file (it is auto-generated).
// Instead, edit message-cpp.tmpl and regenerate.

#ifndef __SCAG_PVSS_PVAP_BC_GETPROF_HPP__
#define __SCAG_PVSS_PVAP_BC_GETPROF_HPP__

#include "util/int.h"
#include <string>
#include "scag/pvss/api/pvap/Exceptions.h"
#include "scag/pvss/api/packets/GetProfileCommand.h"





namespace scag2{
namespace pvss{
namespace pvap{

class PVAPPROF;

class BC_GETPROF
{
protected:

public:
    BC_GETPROF() :
    owned_(true),
    data_(new GetProfileCommand)
    {
    }

    BC_GETPROF( GetProfileCommand* other ) :
    owned_(false),
    data_(other)
    {
    }

    ~BC_GETPROF() {
        if ( data_ && owned_ ) delete data_;
    }

    void clear()
    {
        if ( ! data_ ) return;
        data_->clear();
    }

    GetProfileCommand* pop() {
        GetProfileCommand* rv = data_;
        data_ = 0;
        return rv;
    }

    std::string toString() const
    {
        return data_ ? data_->toString() : "";
    }

    template < class DataStream >
        void serialize( const PVAPPROF& proto, DataStream& writer ) const throw (PvapException)
    {
        if ( ! data_ ) return;
        checkFields();
        // mandatory fields
        // optional fields
    }

    template <class DataStream> void deserialize( PVAPPROF& proto, DataStream& reader )
        throw (PvapException)
    {
        if ( ! data_ ) return;
        clear();
        int tag = -1;
        try {
            do {
                // int pos = int(reader.getPos());
                tag = reader.readTag();
                // printf( "read pos=%d field=%d\n", pos, tag );
                if ( tag == -1 ) break;
                switch(tag) {
                default:
                    throw InvalidFieldTypeException(data_->isRequest(),"BC_GETPROF", getSeqNum(),tag);
                }
            } while ( true );
        } catch ( exceptions::IOException e ) {
            throw PvapSerializationException( data_->isRequest(),
                                              getSeqNum(),
                                              "reading field tag=%d of BC_GETPROF: %s",
                                              tag, e.what() );
        }
        checkFields();
    }

    uint32_t getSeqNum() const {
        return
        uint32_t(-1);
    }


protected:
    void checkFields() const throw (PvapException)
    {
        // using parent check
        if ( !data_->isValid() ) {
            throw MessageIsBrokenException(data_->isRequest(), getSeqNum(), "message BC_GETPROF is broken: %s",data_->toString().c_str());
        }
    }

private:
    BC_GETPROF( const BC_GETPROF& );
    BC_GETPROF& operator = ( const BC_GETPROF& );

protected:
    //static const uint8_t versionMajor=2;
    //static const uint8_t versionMinor=0;

    bool                owned_;
    GetProfileCommand* data_;

};

} // namespace scag2
} // namespace pvss
} // namespace pvap
#endif
