// NOTE: Do NOT edit this file (it is auto-generated).
// Instead, edit message-cpp.tmpl and regenerate.

#ifndef __SCAG_PVSS_PVAP_PC_BATCH_RESP_HPP__
#define __SCAG_PVSS_PVAP_PC_BATCH_RESP_HPP__

#include "util/int.h"
#include <string>
#include "scag/pvss/api/pvap/Exceptions.h"

// #include "scag/pvss/api/pvap/BatchCmdArray.h"
#include "scag/pvss/api/pvap/BatchResponseFiller.h"
#include "scag/pvss/api/packets/BatchResponse.h"





namespace scag2{
namespace pvss{
namespace pvap{

class PVAP;

class PC_BATCH_RESP
{
protected:
    static const int statusValueTag = 1;
    static const int batchContentTag = 38;

public:
    PC_BATCH_RESP( int seqNum ) :
    owned_(true),
    data_(new BatchResponse(seqNum))
    {
    }

    PC_BATCH_RESP( BatchResponse* other ) :
    owned_(false),
    data_(other)
    {
    }

    ~PC_BATCH_RESP() {
        if ( data_ && owned_ ) delete data_;
    }

    void clear()
    {
        if ( ! data_ ) return;
        data_->clear();
    }

    BatchResponse* pop() {
        BatchResponse* rv = data_;
        data_ = 0;
        return rv;
    }

    std::string toString() const
    {
        return data_ ? data_->toString() : "";
    }

    template < class DataStream >
        void serialize( const PVAP& proto, DataStream& writer ) const /* throw (PvapException) */ 
    {
        if ( ! data_ ) return;
        checkFields();
        // mandatory fields
        try {
            // printf( "write pos=%d field=%d\n", ds.getPos(), statusValueTag );
            writer.writeTag(statusValueTag);
            writer.writeByteLV(data_->getStatusValue());
        } catch ( exceptions::IOException e ) {
            throw PvapSerializationException( data_->isRequest(),
                                              data_->getSeqNum(),
                                              "writing field statusValue in PC_BATCH_RESP: %s",
                                              e.what() );
        }
        try {
            // printf( "write pos=%d field=%d\n", ds.getPos(), batchContentTag );
            writer.writeTag(batchContentTag);
            {
                BatchResponseFiller helper( data_ );
                helper.serialize( proto, writer );
 
            }
        } catch ( exceptions::IOException e ) {
            throw PvapSerializationException( data_->isRequest(),
                                              data_->getSeqNum(),
                                              "writing field batchContent in PC_BATCH_RESP: %s",
                                              e.what() );
        }
        // optional fields
    }

    template <class DataStream> void deserialize( PVAP& proto, DataStream& reader )
        /* throw (PvapException) */ 
    {
        if ( ! data_ ) return;
        clear();
        int tag = -1;
        try {
            do {
                // int pos = int(reader.getPos());
                tag = reader.readTag();
                // printf( "read pos=%d field=%d\n", pos, tag );
                if ( tag == -1 ) break;
                switch(tag) {
                case statusValueTag: {
                    data_->setStatusValue(reader.readByteLV());
                    break;
                }
                case batchContentTag: {
                    BatchResponseFiller helper(data_);
                    helper.deserialize(proto,reader);
                    break;
                }
                default:
                    throw InvalidFieldTypeException(data_->isRequest(),"PC_BATCH_RESP", data_->getSeqNum(),tag);
                }
            } while ( true );
        } catch ( exceptions::IOException e ) {
            throw PvapSerializationException( data_->isRequest(),
                                              data_->getSeqNum(),
                                              "reading field tag=%d of PC_BATCH_RESP: %s",
                                              tag, e.what() );
        }
        checkFields();
    }

    uint32_t getSeqNum() const {
        return data_ ? data_->getSeqNum() : uint32_t(-1);
    }

protected:
    void checkFields() const /* throw (PvapException) */ 
    {
        // using parent check
        if ( !data_->isValid() ) {
            throw MessageIsBrokenException(data_->isRequest(), data_->getSeqNum(), "message PC_BATCH_RESP is broken: %s",data_->toString().c_str());
        }
    }

private:
    PC_BATCH_RESP( const PC_BATCH_RESP& );
    PC_BATCH_RESP& operator = ( const PC_BATCH_RESP& );

protected:
    //static const uint8_t versionMajor=2;
    //static const uint8_t versionMinor=0;

    bool                owned_;
    BatchResponse* data_;

};

} // namespace scag2
} // namespace pvss
} // namespace pvap
#endif
