// NOTE: Do NOT edit this file (it is auto-generated).
// Instead, edit message-cpp.tmpl and regenerate.

#ifndef __SCAG_PVSS_PVAP_PC_PING_HPP__
#define __SCAG_PVSS_PVAP_PC_PING_HPP__

#include "util/int.h"
#include <string>
#include "scag/pvss/api/pvap/Exceptions.h"
#include "scag/pvss/api/packets/PingRequest.h"





namespace scag2{
namespace pvss{
namespace pvap{

class PVAP;

class PC_PING
{
protected:

public:
    PC_PING( int seqNum ) :
    owned_(true),
    data_(new PingRequest(seqNum))
    {
    }

    PC_PING( PingRequest* other ) :
    owned_(false),
    data_(other)
    {
    }

    ~PC_PING() {
        if ( data_ && owned_ ) delete data_;
    }

    void clear()
    {
        if ( ! data_ ) return;
        data_->clear();
    }

    PingRequest* pop() {
        PingRequest* rv = data_;
        data_ = 0;
        return rv;
    }

    std::string toString() const
    {
        return data_ ? data_->toString() : "";
    }

    template < class DataStream >
        void serialize( const PVAP& proto, DataStream& writer ) const /* throw (PvapException) */ 
    {
        if ( ! data_ ) return;
        checkFields();
        // mandatory fields
        // optional fields
    }

    template <class DataStream> void deserialize( PVAP& proto, DataStream& reader )
        /* throw (PvapException) */ 
    {
        if ( ! data_ ) return;
        clear();
        int tag = -1;
        try {
            do {
                // int pos = int(reader.getPos());
                tag = reader.readTag();
                // printf( "read pos=%d field=%d\n", pos, tag );
                if ( tag == -1 ) break;
                switch(tag) {
                default:
                    throw InvalidFieldTypeException(data_->isRequest(),"PC_PING", data_->getSeqNum(),tag);
                }
            } while ( true );
        } catch ( exceptions::IOException e ) {
            throw PvapSerializationException( data_->isRequest(),
                                              data_->getSeqNum(),
                                              "reading field tag=%d of PC_PING: %s",
                                              tag, e.what() );
        }
        checkFields();
    }

    uint32_t getSeqNum() const {
        return data_ ? data_->getSeqNum() : uint32_t(-1);
    }

protected:
    void checkFields() const /* throw (PvapException) */ 
    {
        // using parent check
        if ( !data_->isValid() ) {
            throw MessageIsBrokenException(data_->isRequest(), data_->getSeqNum(), "message PC_PING is broken: %s",data_->toString().c_str());
        }
    }

private:
    PC_PING( const PC_PING& );
    PC_PING& operator = ( const PC_PING& );

protected:
    //static const uint8_t versionMajor=2;
    //static const uint8_t versionMinor=0;

    bool                owned_;
    PingRequest* data_;

};

} // namespace scag2
} // namespace pvss
} // namespace pvap
#endif
