
#
# $Id$
#
#

#LDFLAGS := $(LDFLAGS)

PACKAGE := eyeline.sua.sua_layer.lm_subsystem.lm_commands

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules
