#
# $Id$
#

CFLAGS := -I. -I../asn1rt $(CFLAGS)
CXXFLAGS := $(CXXFLAGS)
PACKAGE := inman.codec_uss

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules
