/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c,v 1.10 2004/10/08 23:39:17 rstory Exp $
 *
 * $Id$
 */
#ifndef ROUTEERRTABLE_OIDS_H
#define ROUTEERRTABLE_OIDS_H


/* column number definitions for table routeErrTable */
#define ROUTEERRTABLE_OID         1,3,6,1,4,1,26757,2,13
#define COLUMN_ROUTEERRINDEX      1
#define COLUMN_ROUTEERRCODE       2
#define COLUMN_ROUTEERRID         3
#define COLUMN_ROUTEERRCOUNT      4

#define ROUTEERRTABLE_MIN_COL   COLUMN_ROUTEERRINDEX
#define ROUTEERRTABLE_MAX_COL   COLUMN_ROUTEERRCOUNT


#endif

