/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.12 $ of : mfd-data-access.m2c,v $
 *
 * $Id$
 */
#ifndef ROUTEERRTABLE_DATA_ACCESS_H
#define ROUTEERRTABLE_DATA_ACCESS_H

namespace scag2 {
namespace snmp {
namespace routeerrtable {


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table routeErrTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * routeErrTable is subid 11 of msag.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.26757.2.13, length: 9
*/


    int routeErrTable_init_data(routeErrTable_registration_ptr routeErrTable_reg);


/*
 * TODO:180:o: Review routeErrTable cache timeout.
 * The number of seconds before the cache times out
 */

void routeErrTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
int routeErrTable_cache_load(netsnmp_container *container);
void routeErrTable_cache_free(netsnmp_container *container);
int routeErrTable_row_prep( routeErrTable_rowreq_ctx *rowreq_ctx);


}}}

#endif
