// NOTE: Do NOT edit this file (it is auto-generated).
// Instead, edit message-cpp.tmpl and regenerate.

#ifndef __SCAG_PVSS_PVAP_PC_AUTH_HPP__
#define __SCAG_PVSS_PVAP_PC_AUTH_HPP__

#include "util/int.h"
#include <string>
#include "Exceptions.h"


namespace scag{
namespace pvss{
namespace pvap{

class PC_AUTH  {
public:
  PC_AUTH()
  {
    Clear();
  }
  void Clear()
  {
    protocolVersionFlag=false;
    loginFlag=false;
    passwordFlag=false;
    nameFlag=false;
  }

  std::string toString()const
  {
    std::string rv;
    char buf[32];
		sprintf(buf,"seqNum=%d",seqNum);
		rv+=buf;
    if(protocolVersionFlag)
    {
      rv+=";protocolVersion=";
      sprintf(buf,"%u",(unsigned int)protocolVersion);
      rv+=buf;
    }
    if(loginFlag)
    {
      rv+=";login=";
      rv+=login;
    }
    if(passwordFlag)
    {
      rv+=";password=";
      rv+=password;
    }
    if(nameFlag)
    {
      rv+=";name=";
      rv+=name;
    }
    return rv;
  }

  template <class DataStream>
  uint32_t length()const
  {
    uint32_t rv=0;
    if(protocolVersionFlag)
    {
      rv+=DataStream::tagTypeSize;
      rv+=DataStream::lengthTypeSize;
      rv+=DataStream::fieldSize(protocolVersion);
    }
    if(loginFlag)
    {
      rv+=DataStream::tagTypeSize;
      rv+=DataStream::lengthTypeSize;
      rv+=DataStream::fieldSize(login);
    }
    if(passwordFlag)
    {
      rv+=DataStream::tagTypeSize;
      rv+=DataStream::lengthTypeSize;
      rv+=DataStream::fieldSize(password);
    }
    if(nameFlag)
    {
      rv+=DataStream::tagTypeSize;
      rv+=DataStream::lengthTypeSize;
      rv+=DataStream::fieldSize(name);
    }

    return rv;
  }
  uint8_t getProtocolVersion()const
  {
    if(!protocolVersionFlag)
    {
      throw FieldIsNullException("protocolVersion");
    }
    return protocolVersion;
  }
  void setProtocolVersion(uint8_t value)
  {
    protocolVersion=value;
    protocolVersionFlag=true;
  }
  bool hasProtocolVersion()const
  {
    return protocolVersionFlag;
  }
  const std::string& getLogin()const
  {
    if(!loginFlag)
    {
      throw FieldIsNullException("login");
    }
    return login;
  }
  void setLogin(const std::string& value)
  {
    login=value;
    loginFlag=true;
  }
  bool hasLogin()const
  {
    return loginFlag;
  }
  const std::string& getPassword()const
  {
    if(!passwordFlag)
    {
      throw FieldIsNullException("password");
    }
    return password;
  }
  void setPassword(const std::string& value)
  {
    password=value;
    passwordFlag=true;
  }
  bool hasPassword()const
  {
    return passwordFlag;
  }
  const std::string& getName()const
  {
    if(!nameFlag)
    {
      throw FieldIsNullException("name");
    }
    return name;
  }
  void setName(const std::string& value)
  {
    name=value;
    nameFlag=true;
  }
  bool hasName()const
  {
    return nameFlag;
  }

  template <class DataStream>
  void serialize(DataStream& ds)const
  {
    if(!protocolVersionFlag)
    {
      throw MandatoryFieldMissingException("protocolVersion");
    }
    if(!loginFlag)
    {
      throw MandatoryFieldMissingException("login");
    }
    if(!passwordFlag)
    {
      throw MandatoryFieldMissingException("password");
    }
    if(!nameFlag)
    {
      throw MandatoryFieldMissingException("name");
    }
    // checking profile type
    //ds.writeByte(versionMajor);
    //ds.writeByte(versionMinor);
    //ds.writeInt32(seqNum);
    ds.writeTag(protocolVersionTag);
    ds.writeByteLV(protocolVersion);
    ds.writeTag(loginTag);
    ds.writeStrLV(login);
    ds.writeTag(passwordTag);
    ds.writeStrLV(password);
    ds.writeTag(nameTag);
    ds.writeStrLV(name);
    //ds.writeTag(DataStream::endOfMessage_tag);
  }

  template <class DataStream>
  void deserialize(DataStream& ds)
  {
    Clear();
    bool endOfMessage=false;
    //uint8_t rdVersionMajor=ds.readByte();
    //uint8_t rdVersionMinor=ds.readByte();
    //if(rdVersionMajor!=versionMajor)
    //{
    //  throw IncompatibleVersionException("PC_AUTH");
    //}
    //seqNum=ds.readInt32();
    while(!endOfMessage)
    {
      uint32_t tag=ds.readTag();
      switch(tag)
      {
        case protocolVersionTag:
        {
          if(protocolVersionFlag)
          {
            throw DuplicateFieldException("protocolVersion");
          }
          protocolVersion=ds.readByteLV();
          protocolVersionFlag=true;
        }break;
        case loginTag:
        {
          if(loginFlag)
          {
            throw DuplicateFieldException("login");
          }
          login=ds.readStrLV();
          loginFlag=true;
        }break;
        case passwordTag:
        {
          if(passwordFlag)
          {
            throw DuplicateFieldException("password");
          }
          password=ds.readStrLV();
          passwordFlag=true;
        }break;
        case nameTag:
        {
          if(nameFlag)
          {
            throw DuplicateFieldException("name");
          }
          name=ds.readStrLV();
          nameFlag=true;
        }break;
        case DataStream::endOfMessage_tag:
          endOfMessage=true;
          break;
        default:
          //if(rdVersionMinor==versionMinor)
          //{
          //  throw UnexpectedTag("PC_AUTH",tag);
          //}
          ds.skip(ds.readLength());
      }
    }
    if(!protocolVersionFlag)
    {
      throw MandatoryFieldMissingException("protocolVersion");
    }
    if(!loginFlag)
    {
      throw MandatoryFieldMissingException("login");
    }
    if(!passwordFlag)
    {
      throw MandatoryFieldMissingException("password");
    }
    if(!nameFlag)
    {
      throw MandatoryFieldMissingException("name");
    }
    // checking profile type
  }

  uint32_t getSeqNum()const
  {
    return seqNum;
  }
 
  void setSeqNum(uint32_t value)
  {
    seqNum=value;
  }

protected:
  //static const uint8_t versionMajor=2;
  //static const uint8_t versionMinor=0;

  static const uint32_t protocolVersionTag=15;
  static const uint32_t loginTag=16;
  static const uint32_t passwordTag=17;
  static const uint32_t nameTag=18;

  uint32_t seqNum;

  uint8_t protocolVersion;
  std::string login;
  std::string password;
  std::string name;

  bool protocolVersionFlag;
  bool loginFlag;
  bool passwordFlag;
  bool nameFlag;
};

}
}
}
#endif
