
#
# $Id$
#
#

CXXFLAGS := $(CXXFLAGS) -I. -I$(SMSC_SRCDIR)/core/sinchronization -I$(SMSC_SRCDIR)/sms -I$(ORACLE_HOME)/rdbms/demo -I$(ORACLE_HOME)/network/public -Iutil
PACKAGE := store

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules


	


