package mobi.eyeline.informer.admin.delivery.protogen.protocol;

import mobi.eyeline.protogen.framework.*;
import java.io.IOException;



/**
 * This class was generated by protogen, do not edit it
 */
public class GetDeliveryStateResp implements PDU {
  int seqNum;
  Connection connection;
 
  DeliveryState state;
  boolean stateFlag=false;
  DeliveryStatistics stats;
  boolean statsFlag=false;

  public GetDeliveryStateResp() {
  }
 

  public GetDeliveryStateResp(int seqNum, DeliveryState state , DeliveryStatistics stats) {
 
    this.seqNum = seqNum;
    this.state = state;
    this.stateFlag = true;
    this.stats = stats;
    this.statsFlag = true;
  }
 
  public int getTag() {
    return 42;
  }

  public void clear() {
    stateFlag=false;
    statsFlag=false;
  }
 
  public void debug(StringBuilder sb) {
    sb.append("seqNum=").append(seqNum).append(';');

    if(stateFlag) { sb.append("state=") .append('('); state.debug(sb); sb.append(')').append(';'); }

    if(statsFlag) { sb.append("stats=") .append('('); stats.debug(sb); sb.append(')'); }
  }
 
  public String toString() {
    StringBuilder sb=new StringBuilder(128);
    sb.append("GetDeliveryStateResp:");
    debug(sb);
    return sb.toString();
  }

  public int getSeqNum() {
    return seqNum;
  }

  public void setSeqNum(int seqNum) {
    this.seqNum = seqNum;
  }
 
  public int assignSeqNum() {
    seqNum = PDU.seqGenerator.incrementAndGet();
    return seqNum;
  }
 
  public Connection getConnection() {
    return connection;
  }
 
  public void setConnection( Connection con ) {
    connection = con;
  }

  public DeliveryState getState() throws AccessToUndefinedFieldException {
    if(!stateFlag) throw new AccessToUndefinedFieldException("state");
    return state;
  }

  public void setState(DeliveryState state) {
    this.state = state;
    this.stateFlag = true;
  }
 
  public boolean hasState() {
    return stateFlag;
  }
  public DeliveryStatistics getStats() throws AccessToUndefinedFieldException {
    if(!statsFlag) throw new AccessToUndefinedFieldException("stats");
    return stats;
  }

  public void setStats(DeliveryStatistics stats) {
    this.stats = stats;
    this.statsFlag = true;
  }
 
  public boolean hasStats() {
    return statsFlag;
  }

  public void encode(BufferWriter writer) throws IOException {
    if(stateFlag) {
      writer.writeTag(2); // tag id
      {
        int pos = writer.size();
        writer.writeLength(0);
        int off = writer.size();
        state.encode(writer);
        writer.replaceLength((writer.size()-off), pos);
      }
    }  else throw new MissingMandatoryFieldException("state");
    if(statsFlag) {
      writer.writeTag(3); // tag id
      {
        int pos = writer.size();
        writer.writeLength(0);
        int off = writer.size();
        stats.encode(writer);
        writer.replaceLength((writer.size()-off), pos);
      }
    }  else throw new MissingMandatoryFieldException("stats");
    writer.writeTag(0xFF); // end message tag
  }

  public void decode(BufferReader reader) throws IOException {
    while( true ) {
      int tag = reader.readTag();
      if( tag == 0xFF ) break;
      switch( tag ) {
        case 2: {
          state = new DeliveryState();
          int sz=reader.readLength();
          state.decode(reader);
          stateFlag=true;
        } break;
        case 3: {
          stats = new DeliveryStatistics();
          int sz=reader.readLength();
          stats.decode(reader);
          statsFlag=true;
        } break;
        default:
          throw new IOException( "unknown tagId: "+tag +" seqnum: "+seqNum +" msg: "+GetDeliveryStateResp.class.getName());      }
    }
  }
}
