// $ANTLR 2.7.1: "parser.g" -> "CommandParser.java"$

package ru.novosoft.smsc.admin.console.parser;

/*
 * Parser code generated by ANTLR
 */

import ru.novosoft.smsc.admin.console.Command;
import ru.novosoft.smsc.admin.console.CommandContext;

import ru.novosoft.smsc.admin.console.commands.*;


public interface CommandParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int ACT_ADD = 4;
	int ACT_ALTER = 5;
	int ACT_DELETE = 6;
	int ACT_LIST = 7;
	int ACT_VIEW = 8;
	int ACT_APPLY = 9;
	int ACT_SHOW = 10;
	int TGT_ALIAS = 11;
	int TGT_ROUTE = 12;
	int TGT_PROFILE = 13;
	int TGT_SUBJECT = 14;
	int TGT_PRINCIPAL = 15;
	int TGT_DL = 16;
	int TGT_DLSUB = 17;
	int TGT_DLMEM = 18;
	int OPT_HIDE = 19;
	int OPT_NOHIDE = 20;
	int OPT_BILL = 21;
	int OPT_NOBILL = 22;
	int OPT_ARCH = 23;
	int OPT_NOARCH = 24;
	int OPT_ALLOW = 25;
	int OPT_DENY = 26;
	int OPT_RCPT = 27;
	int OPT_NORCPT = 28;
	int OPT_SRC = 29;
	int OPT_DST = 30;
	int OPT_MASK = 31;
	int OPT_SUBJ = 32;
	int OPT_SVCID = 33;
	int OPT_PRI = 34;
	int OPT_DEFSME = 35;
	int OPT_REPORT = 36;
	int VAL_FULL = 37;
	int VAL_NONE = 38;
	int OPT_ENCODE = 39;
	int VAL_DEF = 40;
	int VAL_UCS2 = 41;
	int OPT_NLIST = 42;
	int OPT_NELEM = 43;
	int OPT_OWNER = 44;
	int OPT_LOCALE = 45;
	int OPT_ACTIVE = 46;
	int OPT_INACTIVE = 47;
	int WS = 48;
	int STR = 49;
	int QSTR = 50;
	int STR_WS = 51;
	int STR_CHR = 52;
	int COMMA = 53;
	int ESC = 54;
	int DIGIT = 55;
}
