// $ANTLR 2.7.1: "parser.g" -> "CommandParser.java"$

package ru.novosoft.smsc.admin.console.parser;

/*
 * Parser code generated by ANTLR
 */

import ru.novosoft.smsc.admin.console.Command;
import ru.novosoft.smsc.admin.console.CommandContext;

import ru.novosoft.smsc.admin.console.commands.*;


public interface CommandParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int ACT_ADD = 4;
	int ACT_ALTER = 5;
	int ACT_DELETE = 6;
	int ACT_LIST = 7;
	int ACT_VIEW = 8;
	int ACT_APPLY = 9;
	int TGT_ALIAS = 10;
	int TGT_ROUTE = 11;
	int TGT_PROFILE = 12;
	int TGT_SUBJECT = 13;
	int OPT_BILL = 14;
	int OPT_NOBILL = 15;
	int OPT_ARCH = 16;
	int OPT_NOARCH = 17;
	int OPT_ALLOW = 18;
	int OPT_DENY = 19;
	int OPT_SRC = 20;
	int OPT_DST = 21;
	int OPT_MASK = 22;
	int OPT_SUBJ = 23;
	int OPT_SVCID = 24;
	int OPT_PRI = 25;
	int OPT_DEFSME = 26;
	int OPT_REPORT = 27;
	int OPT_ENCODE = 28;
	int WS = 29;
	int STRING = 30;
	int ID = 31;
	int NUMBER = 32;
	int ADDRESS = 33;
	int COMMA = 34;
	int ESC = 35;
	int DIGIT = 36;
	int OPT_HIDE = 37;
	int OPT_NOHIDE = 38;
}
