/*
 * Note: this file originally auto-generated by mbi2c using
 *       version : 1.5.2.2 $ of : subagent.m2c,v $
 */
/* standard Net-SNMP includes */

#define USING_AGENTX_SUBAGENT_MODULE 1

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "smeStatTable.hpp"

#include "SmeStatTableSubAgent.hpp"
#include <unistd.h>

namespace smsc{
namespace snmp{
namespace smestattable{

static int keep_running;
static smsc::smeman::SmeManager* smeManPtr=0;
static smsc::stat::SmeStats* smeStatsPtr=0;


smsc::smeman::SmeManager* getSmeMan()
{
  return smeManPtr;
}

smsc::stat::SmeStats* getSmeStats()
{
  return smeStatsPtr;
}

void SmeStatTableSubagent::Init(smsc::smeman::SmeManager* smeman,smsc::stat::SmeStats* smestats)
{
  smeManPtr=smeman;
  smeStatsPtr=smestats;
}


void SmeStatTableSubagent::Register()
{
  se_add_pair_to_slist("agent_mode", strdup("UNKNOWNMODE1"), 128);
  se_add_pair_to_slist("agent_mode", strdup("UNKNOWNMODE2"), 129);
  se_add_pair_to_slist("agent_mode", strdup("UNKNOWNMODE3"), 130);
  se_add_pair_to_slist("babystep_mode", strdup("UNKNOWNMODE4"), 160);
  se_add_pair_to_slist("babystep_mode", strdup("UNKNOWNMODE5"), 161);
  init_smeStatTable();
  init_snmp("smeStatTable");
}

void SmeStatTableSubagent::Unregister()
{
  snmp_shutdown("smeStatTable");
}

}//smestattable
}//snmp
}//smsc
