
-- Delete events if no messages exists
DELETE FROM MCISME_EVT_SET WHERE MSG_ID is not NULL and MSG_ID NOT IN
    (SELECT ID FROM MCISME_MSG_SET);
-- Delete events in WAIT_RCPT state (present on SMSC)    
DELETE FROM MCISME_EVT_SET WHERE MSG_ID IN
    (SELECT ID FROM MCISME_MSG_SET WHERE STATE=30);
-- Detach events from messages
UPDATE MCISME_EVT_SET SET MSG_ID=NULL;

-- Delete messages in WAIT_RCPT state (present on SMSC)
DELETE FROM MCISME_MSG_SET WHERE STATE=30;

-- Set all messages current
DELETE FROM MCISME_CUR_MSG;
INSERT INTO MCISME_CUR_MSG 
    SELECT ABONENT, MAX(ID) AS ID FROM MCISME_MSG_SET GROUP BY ABONENT;

-- Re-populate table MCISME_MSG_SET (with distinct abonents & maximum ids)
DELETE FROM MCISME_MSG_SET;
INSERT INTO MCISME_MSG_SET SELECT ID, 0, ABONENT, NULL from MCISME_CUR_MSG;


COMMIT;
QUIT;