
CFLAGS := -I. -I../asn1rt -I../ros $(CFLAGS)
CXXFLAGS := -I. -I../asn1rt -I../ros $(CXXFLAGS)
PACKAGE := mtsmsme.processor.codec

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules
