/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15795 $ of $ 
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "routeStatTable.hpp"
#include "routeStatTable_subagent.hpp"

#include <signal.h>

namespace scag2 {
namespace snmp {
namespace routestattable {

void RouteStatTableSubagent::Register()
{
  log = smsc::logger::Logger::getInstance("snmp.rstat");
  se_add_pair_to_slist("agent_mode", strdup("UNKNOWNMODE6"), 131);
  se_add_pair_to_slist("agent_mode", strdup("UNKNOWNMODE7"), 132);
  se_add_pair_to_slist("agent_mode", strdup("UNKNOWNMODE8"), 133);
  se_add_pair_to_slist("babystep_mode", strdup("UNKNOWNMODE9"), 162);
  se_add_pair_to_slist("babystep_mode", strdup("UNKNOWNMODE10"), 163);
  init_routeStatTable();
  init_snmp("routeStatTable");
}

void RouteStatTableSubagent::Unregister()
{
  snmp_shutdown("routeStatTable");
}


}}}
