#
# $Id$
#

CFLAGS := -I. -I../asn1rt -DASN1_XER_NOT_USED $(CFLAGS)
CXXFLAGS := $(CXXFLAGS)
PACKAGE := inman.codec

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules
