
CFLAGS := -I. -I$(SMSC_SRCDIR)/mtsmsme/processor/asn1rt -I$(SMSC_SRCDIR)/mtsmsme/codec/mapbscode -I$(SMSC_SRCDIR)/mtsmsme/codec/maptscode -I$(SMSC_SRCDIR)/mtsmsme/codec/mapextensiondatatypes -I$(SMSC_SRCDIR)/mtsmsme/codec/mapcommondatatypes $(CFLAGS)
CXXFLAGS := -I. -I$(SMSC_SRCDIR)/mtsmsme/processor/asn1rt -I$(SMSC_SRCDIR)/mtsmsme/codec/mapbscode -I$(SMSC_SRCDIR)/mtsmsme/codec/maptscode -I$(SMSC_SRCDIR)/mtsmsme/codec/mapextensiondatatypes -I$(SMSC_SRCDIR)/mtsmsme/codec/mapcommondatatypes $(CXXFLAGS)
PACKAGE := mtsmsme.codec.maperdatatypes

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules
