#
# $Id$
#
CXXFLAGS := -I. -I../../asn1rt -I../../codecs/map_atih -I../../codec_inc/ros -I../../codec_inc/map $(CXXFLAGS)
CFLAGS := -I. -I../../asn1rt -I../../codecs/map_atih -I../../codec_inc/ros -I../../codec_inc/map $(CFLAGS)
PACKAGE := inman.comp.map_atih

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules
