/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.43.2.3 $ of : mfd-interface.m2c,v $
 *
 * $Id$
 */
/** @defgroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 *
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef SMEERRTABLE_INTERFACE_H
#define SMEERRTABLE_INTERFACE_H

#include "smeErrTable.hpp"


namespace smsc{
namespace snmp{
namespace smeerrtable{

/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _smeErrTable_initialize_interface(smeErrTable_registration_ptr user_ctx,
                                    u_long flags);

smeErrTable_rowreq_ctx * smeErrTable_allocate_rowreq_ctx(void *);
void smeErrTable_release_rowreq_ctx(smeErrTable_rowreq_ctx *rowreq_ctx);

int smeErrTable_index_to_oid(netsnmp_index *oid_idx,
                            smeErrTable_mib_index *mib_idx);
int smeErrTable_index_from_oid(netsnmp_index *oid_idx,
                              smeErrTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void smeErrTable_valid_columns_set(netsnmp_column_info *vc);


}//smeerrtable
}//snmp
}//smsc


#endif /* SMEERRTABLE_INTERFACE_H */
