
CFLAGS := -I. -I../asn1rt $(CFLAGS)
CXXFLAGS := -I. -I../asn1rt $(CXXFLAGS)
PACKAGE := mtsmsme.processor.ulcodec

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules
