#
# $Id$
#

#CXXFLAGS := $(CXXFLAGS)

PACKAGE := inman.srvloader.abcache
#shared libs used
__LIBRARIES := -L$(SMSC_BUILDDIR)/bin -llogger

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules
