
-- ##### Patch for DB created by DBPrepare.sql (v1.50 -> v1.51) #####

-- Additional operative table indecies 

CREATE INDEX SMS_MSG_LAST_TRY_TIME_IDX ON SMS_MSG (LAST_TRY_TIME)
TABLESPACE SMSC_IDX;

CREATE INDEX SMS_MSG_ST_IDX ON SMS_MSG (ST)
TABLESPACE SMSC_IDX;

CREATE INDEX SMS_MSG_MSG_REF_IDX ON SMS_MSG (MSG_REF)
TABLESPACE SMSC_IDX;
