
-- ********************* Statistics tables for SMSC ********************* --

DROP TABLE SMS_STAT_SME_STATE;
CREATE TABLE SMS_STAT_SME_STATE
(
  period       NUMBER(22)     NOT NULL,
  systemid     VARCHAR2(16)   NOT NULL,
  errcode      NUMBER(22)     NOT NULL,
  counter      NUMBER(22)     NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX SMS_STAT_SME_STATE_IDX ON SMS_STAT_SME_STATE (period)
TABLESPACE SMSC_IDX;
CREATE INDEX SMS_STAT_SME_STATE_ID_IDX ON SMS_STAT_SME_STATE (systemid)
TABLESPACE SMSC_IDX;
CREATE INDEX SMS_STAT_SME_STATE_ERR_IDX ON SMS_STAT_SME_STATE (errcode)
TABLESPACE SMSC_IDX;

DROP TABLE SMS_STAT_ROUTE_STATE;
CREATE TABLE SMS_STAT_ROUTE_STATE
(
  period       NUMBER(22)     NOT NULL,
  routeid      VARCHAR2(32)   NOT NULL,
  errcode      NUMBER(22)     NOT NULL,
  counter      NUMBER(22)     NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX SMS_STAT_ROUTE_STATE_IDX ON SMS_STAT_ROUTE_STATE (period)
TABLESPACE SMSC_IDX;
CREATE INDEX SMS_STAT_ROUTE_STATE_ID_IDX ON SMS_STAT_ROUTE_STATE (routeid)
TABLESPACE SMSC_IDX;
CREATE INDEX SMS_STAT_ROUTE_STATE_ERR_IDX ON SMS_STAT_ROUTE_STATE (errcode)
TABLESPACE SMSC_IDX;
