CREATE TABLE SMS_ARC_BACKUP AS SELECT * FROM SMS_ARC;

DROP TABLE SMS_ARC;

CREATE TABLE SMS_ARC
(  
   ID             RAW(8)       NOT NULL,
   OA             VARCHAR2(30) NOT NULL,   
   DA             VARCHAR2(30) NOT NULL,   
   DDA            VARCHAR2(30) NOT NULL,   
   LAST_TRY_TIME  DATE         NULL,
   SUBMIT_TIME    DATE         NOT NULL,   
   SRC_SME_ID     VARCHAR2(15) NULL,
   DST_SME_ID     VARCHAR2(15) NULL,
   ROUTE_ID       VARCHAR2(32) NULL,
   ST             NUMBER(3)    NOT NULL,
   VALID_TIME     DATE         NOT NULL,
   ATTEMPTS       NUMBER(22)   NOT NULL,
   LAST_RESULT    NUMBER(22)   NOT NULL,
   NEXT_TRY_TIME  DATE         NULL, 
   MR             NUMBER(5)    NOT NULL,
   SVC_TYPE       VARCHAR2(6)  NULL,
   DR             NUMBER(3)    NOT NULL,
   BR             NUMBER(3)    NOT NULL,
   SRC_MSC        VARCHAR2(21) NULL,
   SRC_IMSI       VARCHAR2(21) NULL,
   SRC_SME_N      NUMBER(22)   NOT NULL,   
   DST_MSC        VARCHAR2(21) NULL,
   DST_IMSI       VARCHAR2(21) NULL,
   DST_SME_N      NUMBER(22)   NULL,
   SVC_ID         NUMBER(22)   NULL,
   PRTY           NUMBER(22)   NULL, 
   TXT_LENGTH     NUMBER(10)   NULL,
   BODY_LEN       NUMBER(10)   NOT NULL,
   BODY           RAW(1500)    NULL,
   PRIMARY KEY    (ID)
)
ORGANIZATION INDEX TABLESPACE SMSC_IDX INCLUDING ROUTE_ID
OVERFLOW TABLESPACE SMSC_DATA;

insert into sms_arc
select 
   ID,OA,DA,DDA,LAST_TRY_TIME,SUBMIT_TIME,SRC_SME_ID,DST_SME_ID,ROUTE_ID,
   ST,VALID_TIME,ATTEMPTS,LAST_RESULT,NEXT_TRY_TIME,MR,
   SVC_TYPE,DR,BR,SRC_MSC,SRC_IMSI,SRC_SME_N,DST_MSC,
   DST_IMSI,DST_SME_N,SVC_ID,PRTY,TXT_LENGTH,BODY_LEN,BODY
from sms_arc_backup;
