drop table SMS_ACL;
drop table SMS_ACLINFO;

CREATE TABLE SMS_ACLINFO 
(
  ID           INTEGER NOT NULL
  	       CONSTRAINT SMS_ACLINFO_PK PRIMARY KEY USING INDEX TABLESPACE SMSC_IDX,
  NAME         VARCHAR2(32) NOT NULL
  	       CONSTRAINT SMS_ACLINFO_NAME UNIQUE USING INDEX TABLESPACE SMSC_IDX,
  DESCRIPTION  VARCHAR2(128),
  CACHE_TYPE   CHAR(1)
) TABLESPACE SMSC_DATA;


CREATE TABLE SMS_ACL 
(
  ID           INTEGER NOT NULL,
  ADDRESS      VARCHAR2(30) NOT NULL,
  PRIMARY KEY  (ID,ADDRESS),
  FOREIGN KEY  (ID) REFERENCES SMS_ACLINFO (ID) ON DELETE CASCADE
) ORGANIZATION INDEX TABLESPACE SMSC_DATA;

DROP SEQUENCE SMS_ACLINFO_SEQ;
CREATE SEQUENCE SMS_ACLINFO_SEQ INCREMENT BY 1000
START WITH 1 MINVALUE 1 MAXVALUE 1000000 CACHE 100;
