CREATE TABLE SMS_MSG_BACKUP AS SELECT * FROM SMS_MSG;

DROP TABLE SMS_MSG;

CREATE TABLE SMS_MSG
(  
   ID             RAW(8)       NOT NULL,
   ST             NUMBER(3)    NOT NULL,
   SUBMIT_TIME    DATE         NOT NULL,   
   LAST_TRY_TIME  DATE         NULL,
   NEXT_TRY_TIME  DATE         NULL, 
   OA             VARCHAR2(30) NOT NULL,   
   DA             VARCHAR2(30) NOT NULL,   
   DDA            VARCHAR2(30) NOT NULL,   
   ROUTE_ID       VARCHAR2(32) NULL,
   SRC_SME_ID     VARCHAR2(15) NULL,
   DST_SME_ID     VARCHAR2(15) NULL,
   MSG_REF        NUMBER(3)    NULL,
   ATTEMPTS       NUMBER(22)   NOT NULL,
   LAST_RESULT    NUMBER(22)   NOT NULL,
   VALID_TIME     DATE         NOT NULL,
   MR             NUMBER(5)    NOT NULL,
   SVC_TYPE       VARCHAR2(6)  NULL,
   ARC            CHAR(1)      NOT NULL,
   DR             NUMBER(3)    NOT NULL,
   BR             NUMBER(3)    NOT NULL,
   SRC_MSC        VARCHAR2(21) NULL,
   SRC_IMSI       VARCHAR2(21) NULL,
   SRC_SME_N      NUMBER(22)   NOT NULL,   
   DST_MSC        VARCHAR2(21) NULL,
   DST_IMSI       VARCHAR2(21) NULL,
   DST_SME_N      NUMBER(22)   NULL,
   SVC_ID         NUMBER(22)   NULL,
   PRTY           NUMBER(22)   NULL,
   TXT_LENGTH     NUMBER(10)   NULL,
   SEQ_NUM        NUMBER(3)    NOT NULL,
   BODY_LEN       NUMBER(10)   NOT NULL,
   BODY           RAW(1500)    NULL,
   PRIMARY KEY    (ID)
) 
ORGANIZATION INDEX TABLESPACE SMSC_IDX INCLUDING MSG_REF
OVERFLOW TABLESPACE SMSC_DATA
;

insert into sms_msg
select 
    ID,ST,SUBMIT_TIME,LAST_TRY_TIME,NEXT_TRY_TIME,OA,DA,DDA,
    ROUTE_ID,SRC_SME_ID,DST_SME_ID,MSG_REF,ATTEMPTS,LAST_RESULT,
    VALID_TIME,MR,SVC_TYPE,ARC,DR,BR,SRC_MSC,SRC_IMSI,SRC_SME_N,
    DST_MSC,DST_IMSI,DST_SME_N,SVC_ID,PRTY,TXT_LENGTH,SEQ_NUM,
    BODY_LEN,BODY
from sms_msg_backup
;

CREATE INDEX SMS_BILL_UPLOAD_ID_IDX ON SMS_BILL (UPLOAD_ID) 
TABLESPACE SMSC_IDX;
