/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15795 $ of $ 
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "smeStatTable.hpp"
#include "smeStatTable_subagent.hpp"

#include <signal.h>

namespace scag2{
namespace snmp{
namespace smestattable{

void SmeStatTableSubagent::Register()
{
  log = smsc::logger::Logger::getInstance("snmp.sstat");
  smsc_log_debug(log, "SmeStatTableSubagent::Register");
  se_add_pair_to_slist("agent_mode", strdup("UNKNOWNMODE1"), 128);
  se_add_pair_to_slist("agent_mode", strdup("UNKNOWNMODE2"), 129);
  se_add_pair_to_slist("agent_mode", strdup("UNKNOWNMODE3"), 130);
  se_add_pair_to_slist("babystep_mode", strdup("UNKNOWNMODE4"), 160);
  se_add_pair_to_slist("babystep_mode", strdup("UNKNOWNMODE5"), 161);
  init_smeStatTable();
  init_snmp("smeStatTable");
}

void SmeStatTableSubagent::Unregister()
{
  smsc_log_debug(log, "SmeStatTableSubagent::Unregister");
  snmp_shutdown("smeStatTable");
}


}}}
