
#
# $Id$
#
#

PACKAGE := core

CXXFLAGS := $(CXXFLAGS)
#-DDISABLE_ANY_CHECKS

#LDFLAGS=$(LDGLAGS) -Wl,-verbose

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules
