/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id$
 */
#ifndef ROUTEUSSDTABLE_DATA_ACCESS_H
#define ROUTEUSSDTABLE_DATA_ACCESS_H


//using namespace scag2::stat;

namespace scag2 {
namespace snmp {
namespace routeussdtable {


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table routeStatTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * EYELINE-MSAG-MIB::routeStatTable is subid 10 of msag.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.26757.2.12, length: 9
*/


    int routeStatTable_init_data(routeStatTable_registration_ptr routeStatTable_reg);


/*
 * TODO:180:o: Review routeStatTable cache timeout.
 * The number of seconds before the cache times out
 */
//#define ROUTEUSSDTABLE_CACHE_TIMEOUT   60

void routeStatTable_container_init(netsnmp_container* *container_ptr_ptr, netsnmp_cache* cache);
void routeStatTable_container_shutdown(netsnmp_container* container_ptr);

int routeStatTable_cache_load(netsnmp_container* container);
void routeStatTable_cache_free(netsnmp_container* container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int routeStatTable_row_prep( routeStatTable_rowreq_ctx *rowreq_ctx);

}
}
}

#endif /* ROUTEUSSDTABLE_DATA_ACCESS_H */
