SPECROOT=`pwd`
ROOT=$SPECROOT/../../codec
ASN1COPT="-S /home/vic/projects/asn1c/skeletons -fnative-types"
ASN1C=$SPECROOT/asn1c

generate ()
{
  mkdir -p $DIR; cd $DIR; rm -rf *.[ch]; echo Generate in `pwd`
  $ASN1C $ASN1COPT $SPECLIST
  OUT=$?
  if [ $OUT -ne 0 ]; then exit; fi
  find . -type l  -exec rm {} \;
  rm Makefile.am.sample
#  echo OUTLIST=$OUTLIST
  rm $OUTLIST
  OUTLIST=`ls *.[ch]`
}
#
# Generate ROS
#
ROS_SPECLIST=""
ROS_SPECLIST="$ROS_SPECLIST $SPECROOT/ros/Remote-Operations-Information-Objects.asn"
ROS_SPECLIST="$ROS_SPECLIST $SPECROOT/ros/Remote-Operations-Generic-ROS-PDUs.asn"
SPECLIST=$ROS_SPECLIST
OUTLIST=""
DIR=$ROOT/ros
generate
ROS_OUTLIST=$OUTLIST
#
# Generate TCAP
#
TCAP_SPECLIST="$ROS_SPECLIST"
TCAP_SPECLIST="$TCAP_SPECLIST $SPECROOT/tcap/TCAP-EXTERNAL.asn"
TCAP_SPECLIST="$TCAP_SPECLIST $SPECROOT/tcap/TCAPMessages.asn"
TCAP_SPECLIST="$TCAP_SPECLIST $SPECROOT/tcap/DialoguePDUs.asn"
SPECLIST=$TCAP_SPECLIST
OUTLIST=$ROS_OUTLIST
DIR=$ROOT/tcap
generate
TCAP_OUTLIST=$OUTLIST
#
# Generate MAP-BS-Code
#
MAP_BS_CODE_SPECLIST="$SPECROOT/map/MAP-BS-Code.asn"
SPECLIST=$MAP_BS_CODE_SPECLIST
OUTLIST=""
DIR=$ROOT/mapbscode
generate
MAP_BS_CODE_OUTLIST=$OUTLIST
#
# Generate MAP-SS-Code
#
MAP_SS_CODE_SPECLIST="$SPECROOT/map/MAP-SS-Code.asn"
SPECLIST=$MAP_SS_CODE_SPECLIST
OUTLIST=""
DIR=$ROOT/mapsscode
generate
MAP_SS_CODE_OUTLIST=$OUTLIST
#
# Generate MAP-SS-DataTypes
#
MAP_SS_DATATYPES_SPECLIST=""
MAP_SS_DATATYPES_SPECLIST="$MAP_SS_DATATYPES_SPECLIST $SPECROOT/map/MAP-SS-Code.asn"
MAP_SS_DATATYPES_SPECLIST="$MAP_SS_DATATYPES_SPECLIST $SPECROOT/map/MAP-SS-DataTypes.asn"
SPECLIST=$MAP_SS_DATATYPES_SPECLIST
OUTLIST="$MAP_SS_CODE_OUTLIST"
DIR=$ROOT/mapssdatatypes
generate
MAP_SS_DATATYPES_OUTLIST=$OUTLIST
#
# Generate MAP-TS-Code
#
MAP_TS_CODE_SPECLIST="$SPECROOT/map/MAP-TS-Code.asn"
SPECLIST=$MAP_TS_CODE_SPECLIST
OUTLIST=""
DIR=$ROOT/maptscode
generate
MAP_TS_CODE_OUTLIST=$OUTLIST
#
# Generate MAP-ExtensionDataTypes
#
MAP_EXTDT_SPECLIST="$SPECROOT/map/MAP-ExtensionDataTypes.asn"
SPECLIST=$MAP_EXTDT_SPECLIST
OUTLIST=""
DIR=$ROOT/mapextensiondatatypes
generate
MAP_EXTDT_OUTLIST=$OUTLIST
#
# Generate MAP-CommonDataTypes
#
MAP_CDT_SPECLIST=""
MAP_CDT_SPECLIST="$MAP_CDT_SPECLIST $SPECROOT/map/MAP-TS-Code.asn"
MAP_CDT_SPECLIST="$MAP_CDT_SPECLIST $SPECROOT/map/MAP-BS-Code.asn"
MAP_CDT_SPECLIST="$MAP_CDT_SPECLIST $SPECROOT/map/MAP-ExtensionDataTypes.asn"
MAP_CDT_SPECLIST="$MAP_CDT_SPECLIST $SPECROOT/map/MAP-CommonDataTypes.asn"
SPECLIST=$MAP_CDT_SPECLIST
OUTLIST="$MAP_EXTDT_OUTLIST $MAP_TS_CODE_OUTLIST $MAP_BS_CODE_OUTLIST"
DIR=$ROOT/mapcommondatatypes
generate
MAP_CDT_OUTLIST=$OUTLIST
#
# Generate MAP-ER-DataTypes
#
MAP_ERDT_SPECLIST=""
MAP_ERDT_SPECLIST="$MAP_ERDT_SPECLIST $SPECROOT/map/MAP-TS-Code.asn"
MAP_ERDT_SPECLIST="$MAP_ERDT_SPECLIST $SPECROOT/map/MAP-BS-Code.asn"
MAP_ERDT_SPECLIST="$MAP_ERDT_SPECLIST $SPECROOT/map/MAP-CommonDataTypes.asn"
MAP_ERDT_SPECLIST="$MAP_ERDT_SPECLIST $SPECROOT/map/MAP-ExtensionDataTypes.asn"
MAP_ERDT_SPECLIST="$MAP_ERDT_SPECLIST $SPECROOT/map/MAP-ER-DataTypes.asn"
SPECLIST=$MAP_ERDT_SPECLIST
OUTLIST="$MAP_CDT_OUTLIST $MAP_EXTDT_OUTLIST $MAP_TS_CODE_OUTLIST $MAP_BS_CODE_OUTLIST"
DIR=$ROOT/maperdatatypes
generate
MAP_ERDT_OUTLIST=$OUTLIST
#
# Generate MAP-Errors
#
# NOTE: following instruction generate empty directory so comment them
##MAP_ERRORS_SPECLIST="$ROS_SPECLIST"
##MAP_ERRORS_SPECLIST="$MAP_ERRORS_SPECLIST $SPECROOT/map/MAP-TS-Code.asn"
##MAP_ERRORS_SPECLIST="$MAP_ERRORS_SPECLIST $SPECROOT/map/MAP-BS-Code.asn"
##MAP_ERRORS_SPECLIST="$MAP_ERRORS_SPECLIST $SPECROOT/map/MAP-CommonDataTypes.asn"
##MAP_ERRORS_SPECLIST="$MAP_ERRORS_SPECLIST $SPECROOT/map/MAP-ExtensionDataTypes.asn"
##MAP_ERRORS_SPECLIST="$MAP_ERRORS_SPECLIST $SPECROOT/map/MAP-ER-DataTypes.asn"
##MAP_ERRORS_SPECLIST="$MAP_ERRORS_SPECLIST $SPECROOT/map/MAP-Errors.asn"
##SPECLIST=$MAP_ERRORS_SPECLIST
##OUTLIST="$ROS_OUTLIST $MAP_ERDT_OUTLIST $MAP_CDT_OUTLIST $MAP_EXTDT_OUTLIST $MAP_TS_CODE_OUTLIST $MAP_BS_CODE_OUTLIST"
##DIR=$ROOT/maperrors
##generate
##MAP_ERRORS_OUTLIST=$OUTLIST
#
# Generate MAP-SM-DataTypes
#
MAP_SMDT_SPECLIST=""
MAP_SMDT_SPECLIST="$MAP_SMDT_SPECLIST $SPECROOT/map/MAP-TS-Code.asn"
MAP_SMDT_SPECLIST="$MAP_SMDT_SPECLIST $SPECROOT/map/MAP-BS-Code.asn"
MAP_SMDT_SPECLIST="$MAP_SMDT_SPECLIST $SPECROOT/map/MAP-ExtensionDataTypes.asn"
MAP_SMDT_SPECLIST="$MAP_SMDT_SPECLIST $SPECROOT/map/MAP-CommonDataTypes.asn"
MAP_SMDT_SPECLIST="$MAP_SMDT_SPECLIST $SPECROOT/map/MAP-ER-DataTypes.asn"
MAP_SMDT_SPECLIST="$MAP_SMDT_SPECLIST $SPECROOT/map/MAP-SM-DataTypes.asn"
SPECLIST=$MAP_SMDT_SPECLIST
OUTLIST="$MAP_ERDT_OUTLIST $MAP_CDT_OUTLIST $MAP_EXTDT_OUTLIST $MAP_TS_CODE_OUTLIST $MAP_BS_CODE_OUTLIST"
DIR=$ROOT/mapsmdatatypes
generate
MAP_SMDT_OUTLIST=$OUTLIST
#
# Generate MAP-SM-DataTypes-v1
#
MAP_SMDT_V1_SPECLIST=""
MAP_SMDT_V1_SPECLIST="$MAP_SMDT_V1_SPECLIST $SPECROOT/map/MAP-TS-Code.asn"
MAP_SMDT_V1_SPECLIST="$MAP_SMDT_V1_SPECLIST $SPECROOT/map/MAP-BS-Code.asn"
MAP_SMDT_V1_SPECLIST="$MAP_SMDT_V1_SPECLIST $SPECROOT/map/MAP-ExtensionDataTypes.asn"
MAP_SMDT_V1_SPECLIST="$MAP_SMDT_V1_SPECLIST $SPECROOT/map/MAP-CommonDataTypes.asn"
MAP_SMDT_V1_SPECLIST="$MAP_SMDT_V1_SPECLIST $SPECROOT/map/MAP-SM-DataTypes-v1.asn"
SPECLIST=$MAP_SMDT_V1_SPECLIST
OUTLIST="$MAP_CDT_OUTLIST $MAP_EXTDT_OUTLIST $MAP_TS_CODE_OUTLIST $MAP_BS_CODE_OUTLIST"
DIR=$ROOT/mapsmdatatypesv1
generate
MAP_SMDT_V1_OUTLIST=$OUTLIST
#
# Generate MAP-MS-DataTypes
#
MAP_MSDT_SPECLIST=""
MAP_MSDT_SPECLIST="$MAP_MSDT_SPECLIST $SPECROOT/map/MAP-TS-Code.asn"
MAP_MSDT_SPECLIST="$MAP_MSDT_SPECLIST $SPECROOT/map/MAP-BS-Code.asn"
MAP_MSDT_SPECLIST="$MAP_MSDT_SPECLIST $SPECROOT/map/MAP-ExtensionDataTypes.asn"
MAP_MSDT_SPECLIST="$MAP_MSDT_SPECLIST $SPECROOT/map/MAP-CommonDataTypes.asn"
MAP_MSDT_SPECLIST="$MAP_MSDT_SPECLIST $SPECROOT/map/MAP-MS-DataTypes.asn"
SPECLIST=$MAP_MSDT_SPECLIST
OUTLIST="$MAP_CDT_OUTLIST $MAP_EXTDT_OUTLIST $MAP_TS_CODE_OUTLIST $MAP_BS_CODE_OUTLIST"
DIR=$ROOT/mapmsdatatypes
generate
MAP_MSDT_OUTLIST=$OUTLIST
#
# Generate SMS
#
# NOTE: following instruction generate empty directory so comment them
##SMS_SPECLIST="$ROS_SPECLIST"
##SMS_SPECLIST="$SMS_SPECLIST $SPECROOT/map/MAP-SM-DataTypes.asn"
##SMS_SPECLIST="$SMS_SPECLIST $SPECROOT/map/MAP-CommonDataTypes.asn"
##SMS_SPECLIST="$SMS_SPECLIST $SPECROOT/map/MAP-ExtensionDataTypes.asn"
##SMS_SPECLIST="$SMS_SPECLIST $SPECROOT/map/MAP-BS-Code.asn"
##SMS_SPECLIST="$SMS_SPECLIST $SPECROOT/map/MAP-TS-Code.asn"
##SMS_SPECLIST="$SMS_SPECLIST $SPECROOT/map/MAP-ER-DataTypes.asn"
##SMS_SPECLIST="$SMS_SPECLIST $SPECROOT/map/MAP-ShortMessageServiceOperations.asn"
##SPECLIST=$SMS_SPECLIST
##OUTLIST="$ROS_OUTLIST $MAP_SMDT_OUTLIST $MAP_ERDT_OUTLIST $MAP_CDT_OUTLIST $MAP_EXTDT_OUTLIST $MAP_TS_CODE_OUTLIST $MAP_BS_CODE_OUTLIST"
##DIR=$ROOT/sms
##generate
##SMS_OUTLIST=$OUTLIST
#
# Generate UL
#
# NOTE: following instruction generate empty directory so comment them
##UL_SPECLIST="$ROS_SPECLIST"
##UL_SPECLIST="$UL_SPECLIST $SPECROOT/map/MAP-MS-DataTypes.asn"
##UL_SPECLIST="$UL_SPECLIST $SPECROOT/map/MAP-CommonDataTypes.asn"
##UL_SPECLIST="$UL_SPECLIST $SPECROOT/map/MAP-ExtensionDataTypes.asn"
##UL_SPECLIST="$UL_SPECLIST $SPECROOT/map/MAP-BS-Code.asn"
##UL_SPECLIST="$UL_SPECLIST $SPECROOT/map/MAP-TS-Code.asn"
##UL_SPECLIST="$UL_SPECLIST $SPECROOT/map/MAP-ER-DataTypes.asn"
##UL_SPECLIST="$UL_SPECLIST $SPECROOT/map/MAP-MobileServiceOperations.asn"
##SPECLIST=$UL_SPECLIST
##OUTLIST="$ROS_OUTLIST $MAP_MSDT_OUTLIST $MAP_ERDT_OUTLIST $MAP_CDT_OUTLIST $MAP_EXTDT_OUTLIST $MAP_TS_CODE_OUTLIST $MAP_BS_CODE_OUTLIST"
##DIR=$ROOT/ul
##generate
##UL_OUTLIST=$OUTLIST
#
# Generate MAP-CH-DataTypes
#
MAP_CHDT_SPECLIST=""
MAP_CHDT_SPECLIST="$MAP_CHDT_SPECLIST $SPECROOT/map/MAP-SS-Code.asn"
MAP_CHDT_SPECLIST="$MAP_CHDT_SPECLIST $SPECROOT/map/MAP-TS-Code.asn"
MAP_CHDT_SPECLIST="$MAP_CHDT_SPECLIST $SPECROOT/map/MAP-BS-Code.asn"
MAP_CHDT_SPECLIST="$MAP_CHDT_SPECLIST $SPECROOT/map/MAP-ExtensionDataTypes.asn"
MAP_CHDT_SPECLIST="$MAP_CHDT_SPECLIST $SPECROOT/map/MAP-CommonDataTypes.asn"
MAP_CHDT_SPECLIST="$MAP_CHDT_SPECLIST $SPECROOT/map/MAP-MS-DataTypes.asn"
MAP_CHDT_SPECLIST="$MAP_CHDT_SPECLIST $SPECROOT/map/MAP-SS-DataTypes.asn"
MAP_CHDT_SPECLIST="$MAP_CHDT_SPECLIST $SPECROOT/map/MAP-CH-DataTypes.asn"
SPECLIST=$MAP_CHDT_SPECLIST
OUTLIST="$MAP_MSDT_OUTLIST $MAP_SS_DATATYPES_OUTLIST $MAP_CDT_OUTLIST $MAP_EXTDT_OUTLIST $MAP_TS_CODE_OUTLIST $MAP_BS_CODE_OUTLIST $MAP_SS_CODE_OUTLIST"
DIR=$ROOT/mapchdatatypes
generate
MAP_CHDT_OUTLIST=$OUTLIST
#
# Generate CALL
#
# NOTE: following instruction generate empty directory so comment them
##CH_SPECLIST="$ROS_SPECLIST"
##CH_SPECLIST="$CH_SPECLIST $SPECROOT/map/MAP-MS-DataTypes.asn"
##CH_SPECLIST="$CH_SPECLIST $SPECROOT/map/MAP-CommonDataTypes.asn"
##CH_SPECLIST="$CH_SPECLIST $SPECROOT/map/MAP-ExtensionDataTypes.asn"
##CH_SPECLIST="$CH_SPECLIST $SPECROOT/map/MAP-BS-Code.asn"
##CH_SPECLIST="$CH_SPECLIST $SPECROOT/map/MAP-TS-Code.asn"
##CH_SPECLIST="$CH_SPECLIST $SPECROOT/map/MAP-CH-DataTypes.asn"
##CH_SPECLIST="$CH_SPECLIST $SPECROOT/map/MAP-CallHandlingOperations.asn"
##SPECLIST=$CH_SPECLIST
##OUTLIST="$ROS_OUTLIST $MAP_CHDT_OUTLIST $MAP_MSDT_OUTLIST $MAP_CDT_OUTLIST $MAP_EXTDT_OUTLIST $MAP_TS_CODE_OUTLIST $MAP_BS_CODE_OUTLIST"
##DIR=$ROOT/ch
##generate
##CH_OUTLIST=$OUTLIST
