CREATE TABLE SMS_STAT_SMS--PERIOD-- 
(
  period       NUMBER(22)     NOT NULL,
  accepted     NUMBER(22)     NOT NULL,
  rejected     NUMBER(22)     NOT NULL,
  delivered    NUMBER(22)     NOT NULL,
  failed       NUMBER(22)     NOT NULL,
  rescheduled  NUMBER(22)     NOT NULL,
  temporal     NUMBER(22)     NOT NULL,
  peak_i       NUMBER(22)     DEFAULT 0 NOT NULL,
  peak_o       NUMBER(22)     DEFAULT 0 NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX SMS_STAT_SMS_IDX--PERIOD-- ON SMS_STAT_SMS--PERIOD-- (period)
TABLESPACE SMSC_IDX;

CREATE TABLE SMS_STAT_STATE--PERIOD--
(
  period       NUMBER(22)     NOT NULL,
  errcode      NUMBER(22)     NOT NULL,
  counter      NUMBER(22)     NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX SMS_STAT_STATE_IDX--PERIOD-- ON SMS_STAT_STATE--PERIOD-- (period)
TABLESPACE SMSC_IDX;
CREATE INDEX SMS_STAT_STATE_ERR_IDX--PERIOD-- ON SMS_STAT_STATE--PERIOD-- (errcode)
TABLESPACE SMSC_IDX;

CREATE TABLE SMS_STAT_SME--PERIOD--
(
  period       NUMBER(22)     NOT NULL,
  systemid     VARCHAR2(16)   NOT NULL,
  accepted     NUMBER(22)     NOT NULL,
  rejected     NUMBER(22)     NOT NULL,
  delivered    NUMBER(22)     NOT NULL,
  failed       NUMBER(22)     NOT NULL,
  rescheduled  NUMBER(22)     NOT NULL,
  temporal     NUMBER(22)     NOT NULL,	
  peak_i       NUMBER(22)     DEFAULT 0 NOT NULL,
  peak_o       NUMBER(22)     DEFAULT 0 NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX SMS_STAT_SME_IDX--PERIOD-- ON SMS_STAT_SME--PERIOD-- (period)
TABLESPACE SMSC_IDX;
CREATE INDEX SMS_STAT_SME_ID_IDX--PERIOD-- ON SMS_STAT_SME--PERIOD-- (systemid)
TABLESPACE SMSC_IDX;

CREATE TABLE SMS_STAT_SME_STATE--PERIOD--
(
  period       NUMBER(22)     NOT NULL,
  systemid     VARCHAR2(16)   NOT NULL,
  errcode      NUMBER(22)     NOT NULL,
  counter      NUMBER(22)     NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX SMS_STAT_SME_STATE_IDX--PERIOD-- ON SMS_STAT_SME_STATE--PERIOD-- (period)
TABLESPACE SMSC_IDX;
CREATE INDEX SMS_STAT_SME_STATE_ID_IDX--PERIOD-- ON SMS_STAT_SME_STATE--PERIOD-- (systemid)
TABLESPACE SMSC_IDX;
CREATE INDEX SMS_STAT_SME_STATE_ERR_IDX--PERIOD-- ON SMS_STAT_SME_STATE--PERIOD-- (errcode)
TABLESPACE SMSC_IDX;

CREATE TABLE SMS_STAT_ROUTE--PERIOD--
(
  period       NUMBER(22)     NOT NULL,
  routeid      VARCHAR2(32)   NOT NULL,
  accepted     NUMBER(22)     NOT NULL,
  rejected     NUMBER(22)     NOT NULL,
  delivered    NUMBER(22)     NOT NULL,
  failed       NUMBER(22)     NOT NULL,
  rescheduled  NUMBER(22)     NOT NULL,
  temporal     NUMBER(22)     NOT NULL,
  peak_i       NUMBER(22)     DEFAULT 0 NOT NULL,
  peak_o       NUMBER(22)     DEFAULT 0 NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX SMS_STAT_ROUTE_IDX--PERIOD-- ON SMS_STAT_ROUTE--PERIOD-- (period)
TABLESPACE SMSC_IDX;
CREATE INDEX SMS_STAT_ROUTE_ID_IDX--PERIOD-- ON SMS_STAT_ROUTE--PERIOD-- (routeid)
TABLESPACE SMSC_IDX;

CREATE TABLE SMS_STAT_ROUTE_STATE--PERIOD--
(
  period       NUMBER(22)     NOT NULL,
  routeid      VARCHAR2(32)   NOT NULL,
  errcode      NUMBER(22)     NOT NULL,
  counter      NUMBER(22)     NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX SMS_STAT_ROUTE_STATE_IDX--PERIOD-- ON SMS_STAT_ROUTE_STATE--PERIOD-- (period)
TABLESPACE SMSC_IDX;
CREATE INDEX SMS_STAT_ROUTE_STATE_ID_IDX--PERIOD-- ON SMS_STAT_ROUTE_STATE--PERIOD-- (routeid)
TABLESPACE SMSC_IDX;
CREATE INDEX SMS_STAT_ROUTE_STATE_ERR_IDX--PERIOD-- ON SMS_STAT_ROUTE_STATE--PERIOD-- (errcode)
TABLESPACE SMSC_IDX;
