DROP TABLE SMS_STAT_SMS_--PERIOD--;
DROP TABLE SMS_STAT_STATE_--PERIOD--;
DROP TABLE SMS_STAT_SME_--PERIOD--;
DROP TABLE SMS_STAT_SME_STATE_--PERIOD--;
DROP TABLE SMS_STAT_ROUTE_--PERIOD--;
DROP TABLE SMS_STAT_ROUTE_STATE_--PERIOD--;
quit;
