DROP TABLE SMS_STAT_SMS--PERIOD--;
DROP TABLE SMS_STAT_STATE--PERIOD--;
DROP TABLE SMS_STAT_SME--PERIOD--;
DROP TABLE SMS_STAT_SME_STATE--PERIOD--;
DROP TABLE SMS_STAT_ROUTE--PERIOD--;
DROP TABLE SMS_STAT_ROUTE_STATE--PERIOD--;
quit;
