
#
# $Id$
#
#

CXXFLAGS := $(CXXFLAGS) -I$(SMSC_SRCDIR)
PACKAGE := scag.lcm
DEBUG := YES
#LEAKTRACE := YES

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules
