// NOTE: Do NOT edit this file (it is auto-generated).
// Instead, edit message-cpp.tmpl and regenerate.

#ifndef SCAG_BILL_EWALLET_STREAM_TRANSFERRESP_HPP
#define SCAG_BILL_EWALLET_STREAM_TRANSFERRESP_HPP

#include "util/int.h"
#include <string>
#include "scag/bill/ewallet/Status.h"
#include "scag/exc/IOException.h"
#include "scag/bill/ewallet/Exception.h"


namespace scag2 {
namespace bill {
namespace ewallet {
namespace stream {

class Protocol;

class TransferResp
{
protected:
    static const int statusValueTag = 1;
    static const int amountTag = 10;
    static const int chargeThresholdTag = 19;

public:
    TransferResp()
    {
        statusValueFlag = false;
        amountFlag = false;
        chargeThresholdFlag = false;
    }

    ~TransferResp() {
    }

    void clear()
    {
        statusValueFlag=false;
        amountFlag=false;
        chargeThresholdFlag=false;
    }

    std::string toString() const
    {
        std::string res;
        res.reserve(200);
        res.append("TransferResp");
        {
            char buf[40];
            sprintf(buf," seq=%u",unsigned(getSeqNum()));
            res.append(buf);
        }
        if ( statusValueFlag ) {
            res.append(" statusValue=");
            char buf[10]; sprintf(buf,"%u",unsigned(statusValue)); res.append(buf);
        }
        if ( amountFlag ) {
            res.append(" amount=");
            char buf[20]; sprintf(buf,"%d",unsigned(amount)); res.append(buf);
        }
        if ( chargeThresholdFlag ) {
            res.append(" chargeThreshold=");
            char buf[20]; sprintf(buf,"%d",unsigned(chargeThreshold)); res.append(buf);
        }
        return res;
    }

    bool hasStatusValue() const {
        return statusValueFlag;
    }
    uint8_t getStatusValue() const {
        if (!statusValueFlag) {
            throw Exception( excType(), "TransferResp has no field statusValue");
        }
        return statusValue;
    }
    void setStatusValue( uint8_t v ) {
        this->statusValueFlag = true;
        this->statusValue = v;
    }
    bool hasAmount() const {
        return amountFlag;
    }
    int32_t getAmount() const {
        if (!amountFlag) {
            throw Exception( excType(), "TransferResp has no field amount");
        }
        return amount;
    }
    void setAmount( int32_t v ) {
        this->amountFlag = true;
        this->amount = v;
    }
    bool hasChargeThreshold() const {
        return chargeThresholdFlag;
    }
    int32_t getChargeThreshold() const {
        if (!chargeThresholdFlag) {
            throw Exception( excType(), "TransferResp has no field chargeThreshold");
        }
        return chargeThreshold;
    }
    void setChargeThreshold( int32_t v ) {
        this->chargeThresholdFlag = true;
        this->chargeThreshold = v;
    }

    template < class DataStream >
        void serialize( const Protocol& proto, DataStream& writer ) const
    {
        // printf( "serializing %s\n", toString().c_str() );
        checkFields();
        // mandatory fields
        try {
            // printf( "write pos=%d field=%d\n", ds.getPos(), statusValueTag );
            writer.writeTag(statusValueTag);
            writer.writeByteLV(statusValue);
        } catch ( exceptions::IOException e ) {
            throw Exception( excType(),
                             "writing field statusValue in TransferResp: %s",
                             e.what() );
        }
        // optional fields
        if ( amountFlag ) {
            // printf( "write pos=%d field=%d\n", writer.getPos(), amountTag );
            try {
                writer.writeTag(amountTag);
                writer.writeIntLV(amount);
            } catch ( exceptions::IOException e ) {
                throw Exception( excType(),
                                 "writing field amount in TransferResp: %s",
                                 e.what() );
            }
        }
        if ( chargeThresholdFlag ) {
            // printf( "write pos=%d field=%d\n", writer.getPos(), chargeThresholdTag );
            try {
                writer.writeTag(chargeThresholdTag);
                writer.writeIntLV(chargeThreshold);
            } catch ( exceptions::IOException e ) {
                throw Exception( excType(),
                                 "writing field chargeThreshold in TransferResp: %s",
                                 e.what() );
            }
        }
    }


    template <class DataStream>
    void deserialize( Protocol& proto, DataStream& reader )
    {
        clear();
        int tag = -1;
        try {
            do {
                // int pos = int(reader.getPos());
                tag = reader.readTag();
                // printf( "read pos=%d field=%d\n", pos, tag );
                if ( tag == -1 ) break;
                switch(tag) {
                case statusValueTag: {
                    if (statusValueFlag) {
                        throw Exception( excType(),
                                         "duplicate field statusValue of TransferResp" );
                    }
                    statusValue = reader.readByteLV();
                    statusValueFlag = true;
                    break;
                }
                case amountTag: {
                    if (amountFlag) {
                        throw Exception( excType(),
                                         "duplicate field amount of TransferResp" );
                    }
                    amount = reader.readIntLV();
                    amountFlag = true;
                    break;
                }
                case chargeThresholdTag: {
                    if (chargeThresholdFlag) {
                        throw Exception( excType(),
                                         "duplicate field chargeThreshold of TransferResp" );
                    }
                    chargeThreshold = reader.readIntLV();
                    chargeThresholdFlag = true;
                    break;
                }
                default:
                    throw Exception( excType(),
                                     "TransferResp has invalid field:%u", tag );
                }
            } while ( true );
        } catch ( exceptions::IOException e ) {
            throw Exception( excType(),
                             "reading field tag=%u of TransferResp: %s",
                             tag, e.what() );
        }
        printf( "deserialized %s\n", toString().c_str() );
        checkFields();
    }

    int32_t getSeqNum() const { return seqNum_; }
    void setSeqNum( int32_t seqnum ) { seqNum_ = seqnum; }

protected:
    void checkFields() const
    {
        if ( !statusValueFlag ) {
            throw Exception( excType(),
                             "message TransferResp does not have required field statusValue" );
        }
 
    }

private:
    TransferResp( const TransferResp& );
    TransferResp& operator = ( const TransferResp& );

    inline bool isRequest() const {
        return false;
    }

    inline uint8_t excType() const {
        return isRequest() ? Status::BAD_REQUEST : Status::BAD_RESPONSE;
    }

protected:
    int32_t seqNum_;

    uint8_t statusValue;
    int32_t amount;
    int32_t chargeThreshold;

    bool statusValueFlag;
    bool amountFlag;
    bool chargeThresholdFlag;
};

} // namespace scag2
} // namespace bill
} // namespace ewallet
} // namespace stream
#endif
