
CFLAGS := -I. -I$(SMSC_SRCDIR)/mtsmsme/processor/asn1rt $(CFLAGS)
CXXFLAGS := -I. -I$(SMSC_SRCDIR)/mtsmsme/processor/asn1rt  $(CXXFLAGS)
PACKAGE := mtsmsme.codec.maptscode

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules
