/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id$
 *
 * @file msagCounterTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef MSAGCOUNTERTABLE_DATA_GET_H
#define MSAGCOUNTERTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table msagCounterTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * EYELINE-MSAG-MIB::msagCounterTable is subid 4 of msag.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.26757.2.4, length: 9
*/
    /*
     * indexes
     */

    int msagCounterName_get( msagCounterTable_rowreq_ctx *rowreq_ctx, char **msagCounterName_val_ptr_ptr, size_t *msagCounterName_val_ptr_len_ptr );
    int msagCounterValue_get( msagCounterTable_rowreq_ctx *rowreq_ctx, U64 * msagCounterValue_val_ptr );


int msagCounterTable_indexes_set_tbl_idx(msagCounterTable_mib_index *tbl_idx, long msagCounterIndex_val);
int msagCounterTable_indexes_set(msagCounterTable_rowreq_ctx *rowreq_ctx, long msagCounterIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* MSAGCOUNTERTABLE_DATA_GET_H */
/** @} */
