DROP TABLE EMLSME_PROFILES;
CREATE TABLE EMLSME_PROFILES(
  ID NUMBER(9) NOT NULL,
  ADDRESS VARCHAR(21),
  USERNAME VARCHAR(64),
  DAILY_LIMIT NUMBER(9)
)TABLESPACE SMSC_DATA;


CREATE UNIQUE INDEX EMLSME_IDX_ID ON EMLSME_PROFILES(ID)
TABLESPACE SMSC_IDX;

CREATE UNIQUE INDEX EMLSME_IDX_PHONE ON EMLSME_PROFILES(ADDRESS)
TABLESPACE SMSC_IDX;

CREATE UNIQUE INDEX EMLSME_IDX_EMAIL ON EMLSME_PROFILES(USERNAME)
TABLESPACE SMSC_IDX;

DROP TABLE EMLSME_HISTORY;
CREATE TABLE EMLSME_HISTORY(
  USER_ID NUMBER(9) NOT NULL,
  MSG_DATE DATE
);

CREATE INDEX EMLSME_IDX_HISTORY ON EMLSME_HISTORY(MSG_DATE)
TABLESPACE SMSC_IDX;

