
-- ********************* Operative tables for InfoSme ********************* --

DROP SEQUENCE INFOSME_MESSAGES_SEQ;
CREATE SEQUENCE INFOSME_MESSAGES_SEQ INCREMENT BY 1 START WITH 1
MAXVALUE 1000000000000000000 CACHE 20;

DROP TABLE INFOSME_ID_MAPPING;
CREATE TABLE INFOSME_ID_MAPPING
(
    ID		NUMBER		NOT NULL
	        CONSTRAINT INFOSME_ID_MAPPING_PK PRIMARY KEY,
    SMSC_ID	VARCHAR2(64)	NOT NULL,
    TASK_ID	VARCHAR2(256)   NOT NULL
);

CREATE INDEX INFOSME_ID_MAPPING_SMSC_ID_IDX ON INFOSME_ID_MAPPING (SMSC_ID);

DROP TABLE INFOSME_TASKS_STAT;
CREATE TABLE INFOSME_TASKS_STAT
(
    TASK_ID	VARCHAR2(256)   NOT NULL,
    PERIOD	NUMBER(22)	NOT NULL,
    GENERATED	NUMBER(22)	NOT NULL,
    DELIVERED	NUMBER(22)	NOT NULL,
    RETRIED	NUMBER(22)	NOT NULL,
    FAILED	NUMBER(22)	NOT NULL
);

CREATE INDEX INFOSME_ST_ID_PERIOD_IDX ON INFOSME_TASKS_STAT (TASK_ID, PERIOD);

DROP TABLE INFOSME_GENERATING_TASKS;
CREATE TABLE INFOSME_GENERATING_TASKS
(
    TASK_ID	VARCHAR2(256)   NOT NULL
		CONSTRAINT INFOSME_GENERATING_TASKS_PK PRIMARY KEY
);

COMMIT;
QUIT;