
-- ********************* Operative tables for InfoSme ********************* --

DROP SEQUENCE INFOSME_MESSAGES_SEQ;
CREATE SEQUENCE INFOSME_MESSAGES_SEQ INCREMENT BY 1 START WITH 1
MAXVALUE 1000000000000000000 CACHE 20;

DROP TABLE INFOSME_ID_MAPPING;
CREATE TABLE INFOSME_ID_MAPPING
(
    ID		NUMBER		NOT NULL
	        CONSTRAINT INFOSME_ID_MAPPING_PK PRIMARY KEY,
    SMSC_ID	VARCHAR2(64)	NOT NULL,
    TASK_ID	VARCHAR2(256)   NOT NULL
);

CREATE INDEX INFOSME_ID_MAPPING_SMSC_ID_IDX ON INFOSME_ID_MAPPING (SMSC_ID);

DROP TABLE INFOSME_TASKS_STAT;
CREATE TABLE INFOSME_TASKS_STAT
(
    TASK_ID	VARCHAR2(256)   NOT NULL,
    PERIOD	NUMBER(22)	NOT NULL,
    GENERATED	NUMBER(22)	NOT NULL,
    DELIVERED	NUMBER(22)	NOT NULL,
    RETRIED	NUMBER(22)	NOT NULL,
    FAILED	NUMBER(22)	NOT NULL
);

CREATE INDEX INFOSME_ST_ID_PERIOD_IDX ON INFOSME_TASKS_STAT (TASK_ID, PERIOD);

-- ********************* Testing tables for InfoSme ********************* --

DROP TABLE INFOSME_TEST_PROVIDER;
CREATE TABLE INFOSME_TEST_PROVIDER
(
    ABONENT	VARCHAR2(30)	NOT NULL,
    BALANCE     NUMBER(6,2)     NOT NULL,
    DT          DATE            NULL
);

--INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
--VALUES ('.0.1.1', 11.11, NULL);

INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.3', 33.33, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.2', 22.22, NULL);
INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('.0.1.5', 55.55, NULL);
