
-- ********************* Operative tables for InfoSme ********************* --

DROP SEQUENCE INFOSME_MESSAGES_SEQ;
CREATE SEQUENCE INFOSME_MESSAGES_SEQ INCREMENT BY 1 START WITH 1
MAXVALUE 1000000000000000000 CACHE 20;

DROP TABLE INFOSME_ID_MAPPING;
CREATE TABLE INFOSME_ID_MAPPING
(
    ID		NUMBER		NOT NULL
	        CONSTRAINT INFOSME_ID_MAPPING_PK PRIMARY KEY,
    SMSC_ID	VARCHAR2(65)	NOT NULL,
    TASK_ID	VARCHAR2(2000)  NOT NULL
);

CREATE INDEX INFOSME_ID_MAPPING_SMSC_ID_IDX ON INFOSME_ID_MAPPING (SMSC_ID);

-- ********************* Testing tables for InfoSme ********************* --

DROP TABLE INFOSME_TEST_PROVIDER;
CREATE TABLE INFOSME_TEST_PROVIDER
(
    ABONENT	VARCHAR2(30)	NOT NULL,
    BALANCE     NUMBER(6,2)     NOT NULL,
    DT          DATE            NULL
);

INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('+111111', 11.11, NULL);

INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('+222222', 22.22, NULL);

INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('+333333', 33.33, NULL);

INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('+444444', 44.44, NULL);

INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('+555555', 55.55, NULL);

INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('+666666', 66.66, NULL);

INSERT INTO INFOSME_TEST_PROVIDER (ABONENT, BALANCE, DT)
VALUES ('+777777', 77.77, NULL);