DROP TABLE SMS_MSG;
CREATE TABLE SMS_MSG
(	
	ID 		RAW(8) 		NOT NULL,
	ST 		NUMBER(3)	NOT NULL,
	MR 		NUMBER(3)	NULL,
	RM 		NUMBER(3)	NULL,
	OA_LEN 		NUMBER(3)	NOT NULL,
	OA_TON 		NUMBER(3)	NOT NULL,
	OA_NPI 		NUMBER(3)	NOT NULL,
	OA_VAL		VARCHAR(21)	NOT NULL,
	DA_LEN 		NUMBER(3)	NOT NULL,
	DA_TON 		NUMBER(3)	NOT NULL,
	DA_NPI 		NUMBER(3)	NOT NULL,
	DA_VAL 		VARCHAR(21)	NOT NULL,
	VALID_TIME	DATE		NULL,
	WAIT_TIME	DATE		NULL,
	SUBMIT_TIME	DATE		NOT NULL,
	DELIVERY_TIME	DATE		NULL,
	SRR		CHAR(1)		NOT NULL,
	RD		CHAR(1)		NOT NULL,
	ARC		CHAR(1)		NOT NULL,
	PRI		NUMBER(3)	NULL,
	PID		NUMBER(3)	NULL,
	FCS		NUMBER(3)	NULL,
	DCS		NUMBER(3)	NULL,
	UDHI		CHAR(1)		NULL,
	UDL		NUMBER(3)	NULL,
	UD		RAW(200)	NOT NULL
) TABLESPACE SMSC_DATA INITRANS 200 NOLOGGING;

CREATE UNIQUE INDEX SMS_MSG_ID ON SMS_MSG (ID)
TABLESPACE SMSC_IDX NOSORT NOLOGGING;

ALTER TABLE SMS_MSG ADD CONSTRAINT SMS_MSG_PK PRIMARY KEY (ID);

CREATE INDEX SMS_MSG_ST_IDX ON SMS_MSG (ST ASC)
TABLESPACE SMSC_IDX NOCOMPRESS NOLOGGING;

CREATE INDEX SMS_MSG_OA_IDX ON SMS_MSG (OA_LEN, OA_TON, OA_NPI, OA_VAL)
TABLESPACE SMSC_IDX NOCOMPRESS NOLOGGING;

CREATE INDEX SMS_MSG_DA_IDX ON SMS_MSG (DA_LEN, DA_TON, DA_NPI, DA_VAL)
TABLESPACE SMSC_IDX NOCOMPRESS NOLOGGING;

DROP TABLE SMS_ARC;
CREATE TABLE SMS_ARC
(	
	ID 		RAW(8)		NOT NULL,
        ST 		NUMBER(3)	NOT NULL,
	MR 		NUMBER(3)	NULL,
	RM 		NUMBER(3)	NULL,
	OA_LEN 		NUMBER(3)	NOT NULL,
	OA_TON 		NUMBER(3)	NOT NULL,
	OA_NPI 		NUMBER(3)	NOT NULL,
	OA_VAL		VARCHAR(21)	NOT NULL,
	DA_LEN 		NUMBER(3)	NOT NULL,
	DA_TON 		NUMBER(3)	NOT NULL,
	DA_NPI 		NUMBER(3)	NOT NULL,
	DA_VAL 		VARCHAR(21)	NOT NULL,
	VALID_TIME	DATE		NULL,
	WAIT_TIME	DATE		NULL,
	SUBMIT_TIME	DATE		NOT NULL,
	DELIVERY_TIME	DATE		NULL,
	SRR		CHAR(1)		NOT NULL,
	RD		CHAR(1)		NOT NULL,
	PRI		NUMBER(3)	NULL,
	PID		NUMBER(3)	NULL,
	FCS		NUMBER(3)	NULL,
	DCS		NUMBER(3)	NULL,
	UDHI		CHAR(1)		NULL,
	UDL		NUMBER(3)	NULL,
	UD		RAW(200)	NOT NULL
) TABLESPACE SMSC_DATA INITRANS 200 NOLOGGING;

CREATE UNIQUE INDEX SMS_ARC_ID ON SMS_ARC (ID)
TABLESPACE SMSC_IDX NOSORT NOLOGGING;

ALTER TABLE SMS_ARC ADD CONSTRAINT SMS_ARC_PK PRIMARY KEY (ID);


