DROP TABLE SMS_MSG;
CREATE TABLE SMS_MSG
(	
	ID 		RAW(8)	PRIMARY KEY USING INDEX TABLESPACE SMSC_IDX,
	ST 		NUMBER(3)	NOT NULL,
	MR 		NUMBER(3)	NULL,
	RM 		NUMBER(3)	NULL,
	OA_LEN 		NUMBER(3)	NOT NULL,
	OA_TON 		NUMBER(3)	NOT NULL,
	OA_NPI 		NUMBER(3)	NOT NULL,
	OA_VAL		CHAR(21)	NOT NULL,
	DA_LEN 		NUMBER(3)	NOT NULL,
	DA_TON 		NUMBER(3)	NOT NULL,
	DA_NPI 		NUMBER(3)	NOT NULL,
	DA_VAL 		CHAR(21)	NOT NULL,
	VALID_TIME	DATE		NULL,
	WAIT_TIME	DATE		NULL,
	SUBMIT_TIME	DATE		NOT NULL,
	DELIVERY_TIME	DATE		NULL,
	SRR		CHAR(1)		NOT NULL,
	RD		CHAR(1)		NOT NULL,
	PRI		NUMBER(3)	NULL,
	PID		NUMBER(3)	NULL,
	FCS		NUMBER(3)	NULL,
	DCS		NUMBER(3)	NULL,
	UDHI		CHAR(1)		NULL,
	UDL		NUMBER(3)	NULL,
	UD		RAW(200)	NOT NULL
) TABLESPACE SMSC_DATA INITRANS 200 NOLOGGING;

DROP TABLE SMS_ARC;
CREATE TABLE SMS_ARC
(	
	ID 		RAW(8)	PRIMARY KEY USING INDEX TABLESPACE SMSC_IDX,
	ST 		NUMBER(3)	NOT NULL,
	MR 		NUMBER(3)	NULL,
	RM 		NUMBER(3)	NULL,
	OA_LEN 		NUMBER(3)	NOT NULL,
	OA_TON 		NUMBER(3)	NOT NULL,
	OA_NPI 		NUMBER(3)	NOT NULL,
	OA_VAL		CHAR(21)	NOT NULL,
	DA_LEN 		NUMBER(3)	NOT NULL,
	DA_TON 		NUMBER(3)	NOT NULL,
	DA_NPI 		NUMBER(3)	NOT NULL,
	DA_VAL 		CHAR(21)	NOT NULL,
	VALID_TIME	DATE		NULL,
	WAIT_TIME	DATE		NULL,
	SUBMIT_TIME	DATE		NOT NULL,
	DELIVERY_TIME	DATE		NULL,
	SRR		CHAR(1)		NOT NULL,
	RD		CHAR(1)		NOT NULL,
	PRI		NUMBER(3)	NULL,
	PID		NUMBER(3)	NULL,
	FCS		NUMBER(3)	NULL,
	DCS		NUMBER(3)	NULL,
	UDHI		CHAR(1)		NULL,
	UDL		NUMBER(3)	NULL,
	UD		RAW(200)	NOT NULL
) TABLESPACE SMSC_DATA INITRANS 200 NOLOGGING;

