DROP TABLE SMPPGW_STAT;
CREATE TABLE SMPPGW_STAT
(
  period       NUMBER(22)     NOT NULL,
  accepted     NUMBER(22)     NOT NULL,
  rejected     NUMBER(22)     NOT NULL,
  delivered    NUMBER(22)     NOT NULL,
  temperror    NUMBER(22)     NOT NULL,
  permerror    NUMBER(22)     NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX SMPPGW_STAT_IDX ON SMPPGW_STAT (period)
TABLESPACE SMSC_IDX;

DROP TABLE SMPPGW_STAT_ERRORS;
CREATE TABLE SMPPGW_STAT_ERRORS
(
  period       NUMBER(22)     NOT NULL,
  errcode      NUMBER(22)     NOT NULL,
  counter      NUMBER(22)     NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX SMPPGW_STAT_ERR_IDX ON SMPPGW_STAT_ERRORS (period)
TABLESPACE SMSC_IDX;
CREATE INDEX SMPPGW_STAT_ERR_CODE_IDX ON SMPPGW_STAT_ERRORS (errcode)
TABLESPACE SMSC_IDX;

DROP TABLE SMPPGW_STAT_SME;
CREATE TABLE SMPPGW_STAT_SME
(
  period       NUMBER(22)     NOT NULL,
  systemid     VARCHAR2(16)   NOT NULL,
  accepted     NUMBER(22)     NOT NULL,
  rejected     NUMBER(22)     NOT NULL,
  delivered    NUMBER(22)     NOT NULL,
  temperror    NUMBER(22)     NOT NULL,
  permerror    NUMBER(22)     NOT NULL,
  SmsTrOk      NUMBER(22)     NOT NULL,
  SmsTrFailed  NUMBER(22)     NOT NULL,
  SmsTrBilled  NUMBER(22)     NOT NULL,
  UssdTrFromScOk NUMBER(22)     NOT NULL,
  UssdTrFromScFailed NUMBER(22)     NOT NULL,
  UssdTrFromScFailedBilled NUMBER(22)     NOT NULL,
  UssdTrFromSmeOk          NUMBER(22)     NOT NULL,
  UssdTrFromSmeFailed      NUMBER(22)     NOT NULL, 
  UssdTrFromSmeFailedBilled NUMBER(22)     NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX SMPPGW_STAT_SME_IDX ON SMPPGW_STAT_SME (period)
TABLESPACE SMSC_IDX;
CREATE INDEX SMPPGW_STAT_SME_ID_IDX ON SMPPGW_STAT_SME (systemid)
TABLESPACE SMSC_IDX;

DROP TABLE SMPPGW_STAT_SME_ERRORS;
CREATE TABLE SMPPGW_STAT_SME_ERRORS
(
  period       NUMBER(22)     NOT NULL,
  systemid     VARCHAR2(16)   NOT NULL,
  errcode      NUMBER(22)     NOT NULL,
  counter      NUMBER(22)     NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX SMPPGW_STAT_SME_ERR_IDX ON SMPPGW_STAT_SME_ERRORS (period)
TABLESPACE SMSC_IDX;
CREATE INDEX SMPPGW_STAT_SME_ERR_ID_IDX ON SMPPGW_STAT_SME_ERRORS (systemid)
TABLESPACE SMSC_IDX;
CREATE INDEX SMPPGW_STAT_SME_ERR_CODE_IDX ON SMPPGW_STAT_SME_ERRORS (errcode)
TABLESPACE SMSC_IDX;

DROP TABLE SMPPGW_STAT_ROUTE;
CREATE TABLE SMPPGW_STAT_ROUTE
(
  period       NUMBER(22)     NOT NULL,
  routeid      VARCHAR2(32)   NOT NULL,
  accepted     NUMBER(22)     NOT NULL,
  rejected     NUMBER(22)     NOT NULL,
  delivered    NUMBER(22)     NOT NULL,
  temperror    NUMBER(22)     NOT NULL,
  permerror    NUMBER(22)     NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX SMPPGW_STAT_ROUTE_IDX ON SMPPGW_STAT_ROUTE (period)
TABLESPACE SMSC_IDX;
CREATE INDEX SMPPGW_STAT_ROUTE_ID_IDX ON SMPPGW_STAT_ROUTE (routeid)
TABLESPACE SMSC_IDX;

DROP TABLE SMPPGW_STAT_ROUTE_ERRORS;
CREATE TABLE SMPPGW_STAT_ROUTE_ERRORS
(
  period       NUMBER(22)     NOT NULL,
  routeid      VARCHAR2(32)   NOT NULL,
  errcode      NUMBER(22)     NOT NULL,
  counter      NUMBER(22)     NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX SMPPGW_STAT_ROUTE_ERR_IDX ON SMPPGW_STAT_ROUTE_ERRORS (period)
TABLESPACE SMSC_IDX;
CREATE INDEX SMPPGW_STAT_ROUTE_ERR_ID_IDX ON SMPPGW_STAT_ROUTE_ERRORS (routeid)
TABLESPACE SMSC_IDX;
CREATE INDEX SMPPGW_STAT_ROUTE_ERR_ERR_IDX ON SMPPGW_STAT_ROUTE_ERRORS (errcode)
TABLESPACE SMSC_IDX;
