
-- ******************* Welcome Sme tables ******************* --

-- Contains ad messages --
DROP TABLE WSME_AD;
CREATE TABLE WSME_AD
(
   ID          NUMBER(22)     NOT NULL,
   LANG        VARCHAR2(20)   NOT NULL,	-- !!! ACTUAL LANG SHOULD BE SPECIFIED
   AD          VARCHAR2(256)  NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX WSME_AD_IDX ON WSME_AD (ID, LANG) TABLESPACE SMSC_IDX;
ALTER TABLE WSME_AD ADD CONSTRAINT WSME_AD_PK PRIMARY KEY (ID, LANG);

-- Contains visitors by mask --
DROP TABLE WSME_VISITORS;
CREATE TABLE WSME_VISITORS
(
   MASK        VARCHAR2(30)   NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX WSME_VISITORS_IDX ON WSME_VISITORS (MASK) TABLESPACE SMSC_IDX;
ALTER TABLE WSME_VISITORS ADD CONSTRAINT WSME_VISITORS_PK PRIMARY KEY (MASK);

-- Contains languagues by mask --
DROP TABLE WSME_LANGS;
CREATE TABLE WSME_LANGS
(
   MASK        VARCHAR2(30)   NOT NULL,
   LANG        VARCHAR2(20)   NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX WSME_LANGS_IDX ON WSME_LANGS (MASK) TABLESPACE SMSC_IDX;
ALTER TABLE WSME_LANGS ADD CONSTRAINT WSME_LANGS_PK PRIMARY KEY (MASK);

-- Contains visitors history --
DROP TABLE WSME_HISTORY;
CREATE TABLE WSME_HISTORY
(
   MSISDN      VARCHAR2(30)   NOT NULL,
   ST	       NUMBER(4)      NOT NULL,
   ID          NUMBER(22)     NOT NULL,
   MSG_ID      VARCHAR2(65)   NULL,
   LAST_UPDATE DATE           NOT NULL
) TABLESPACE SMSC_DATA;

CREATE INDEX WSME_HISTORY_IDX ON WSME_HISTORY (MSISDN) TABLESPACE SMSC_IDX;
ALTER TABLE WSME_HISTORY ADD CONSTRAINT WSME_HISTORY_PK PRIMARY KEY (MSISDN);

CREATE INDEX WSME_HISTORY_UPDATE_IDX ON WSME_HISTORY (LAST_UPDATE) TABLESPACE SMSC_IDX;

CREATE INDEX WSME_HISTORY_MSG_ID_IDX ON WSME_HISTORY (MSG_ID) TABLESPACE SMSC_IDX;

