
#
# $Id$
#
#

PACKAGE := system.mapio

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

CXXFLAGS:= $(CXXFLAGS)

#ifneq ($(NOMAP),YES)
#ifeq ("$(MACHTYPE)","sparc-sun-solaris")
#CXXFLAGS := $(CXXFLAGS) -DUSE_MAP
#endif
#endif

include $(SMSC_SRCDIR)/conf/module_rules
