
#
# $Id$
#
#

PACKAGE := tests.smpp
__LIBRARIES :=-L$(SMSC_BUILDDIR)/bin -llogger -lutil-xml

ifndef SMSC_SRCDIR
$(error SMSC_SRCDIR is not defined)
endif

include $(SMSC_SRCDIR)/conf/module_rules


	


